### ISSUE TITLE
Direct x 12

### ISSUE THREAD

**Issue by alexis23ange** [decaf-emu/decaf-emu#136]
please go back to dx12 opengl is a huge mess and everything always crashes since you switched

**Comment by VelocityRa** [comment]
Can you be a little more specific? "everything always crashes" isn't very heplful.
The developers had a few reasons to make the switch, the problems you experience are going to be fixed with time, provided you help the process with useful bug reports.

**Comment by RHY3756547** [comment]
Everything always crashed before... NES Remix is the only thing I've tried that sorta works right now.

**Comment by alexis23ange** [comment]
at least tell me you guys are going to rip apart cemu and steal ity's code ? and switch to vulkan aka mantle reborn

**Comment by exjam** [comment]
So many things have changed other than moving to OpenGL. This is an actively developed project with no stable releases, and you must remember that sometimes to move forwards you have to take a step backwards, there is no guarantee that any game will behave the same a month from now than it does now. The whole GX2 implementation was completely rewritten and is now much much better implemented and more accurate to the Wii U, even if things don't look as good that's just a matter of improving the OpenGL driver.

One possible explanation for you seeing more crashes could be that more things crash now, as before many games were ending up in dead/live locks (which to the user would look like its just loading or something) as a bunch of threading issues have been fixed recently. Also as things change completely different code paths could end up being taken in games, it was only recently we fixed all the bugs in the CPU and one of the test applications we use (Amiibo Settings from the NUS) behaved very differently after that.

Regardless, I am closing this issue as it isn't really productive - in the future other graphics backends will be considered (Vulkan will hopefully make DX12 irrelevant and has the advantage of being cross platform but we may still need Mantle for proper OSX support as Apple's OpenGL is wank).

**Comment by alexis23ange** [comment]
the last thing i want is pure vulkan as in most cases direct x 12 is faster and not everyone likes using opengl or open source stuff they rarely trust it so as long as both dx12 and vulkan are in this project soon i will continue to support it and do videos about it but if not im out

**Comment by lioncash** [comment]
Woah, dang, gosh, I'm really sure @exjam wouldn't want to lose such an asset :^)

> as in most cases direct x 12 is faster

Comparing an API versus and unreleased API is a pretty sick meme if I do say so myself.

**Comment by sasukedotca** [comment]
wow, the guy is actually "not willing" to use Open source "stuff" because he doesnt "like" it ?
Man, this emulator is an "open-source stuff" and if you dont like to use GNU softwares, you will have to uninstall/stop using a lot of things among them : 
-Opera/firefox.
-internet since a lot of servers are running linux and apache.
-MKV/DivX and other open source renderers.
-VLC/Media Player Classic.
