### ISSUE TITLE
Update Readme with Dependencies

### ISSUE THREAD

**Issue by tanner-taylor24** [decaf-emu/decaf-emu#137]
I know there has been an issue created similar to this, but I wanted to see if this could get done.

Could the readme be updated with dependencies on what needs to be built? Maybe we could have some submodules of the libraries necessary to build the emulator? I've had trouble building the project.

**Comment by brett19** [comment]
All the dependancies for the project are linked directly to the project via git submodules.  The only 'external dependancies' you should run into would be the Windows SDK.

**Comment by VelocityRa** [comment]
Yeah, [these](https://github.com/decaf-emu/decaf-emu/tree/master/libraries) are the dependencies of the project.
Just do `git submodule update --init --recursive` in the project directory (where the .git folder is located) and you're set. You don't even need to do that if you use Github for Windows.

**Comment by tanner-taylor24** [comment]
oh I'm dumb! That's exactly what I was looking for. Thanks!

**Comment by VelocityRa** [comment]
No problem, you can close the Issue now :)
