### ISSUE TITLE
Wiki and requirements discrepancy?

### ISSUE THREAD

**Issue by tambry** [decaf-emu/decaf-emu#140]
The main README says that you need OpenGL and it works on Windows and Linux, while the wiki indicates that DirectX 12 is used and only works on Windows.
Which is right?

**Comment by exjam** [comment]
README.md, I have never edited the wiki - apparently random people can just come along and do that without needing any permissions.

**Comment by sasukedotca** [comment]
I edited the wiki, My apologies for that, I thought I was helping by clarifying why DX 12 was used at the beginning since a lot of people do not read the readme file.

**Comment by exjam** [comment]
Yeah no worries, it's just I get no notifications about wiki edits - I didn't even know we had a wiki until like a month or two after someone had made the first changes.

I have decided to remove the wiki for now, I don't think we are in need of one right now.
