### ISSUE TITLE
Merging to Dolphin? Any hope?

### ISSUE THREAD

**Issue by timofonic** [decaf-emu/decaf-emu#141]
Hello.

Are there any hopes to merging it with an established project like Dolphin?

If not, why? Would there be a more valid project as Decaf's home? ;)

Kind regards.

**Comment by degasus** [comment]
Nope, there is no need in merging two orthogonal projects.

New home, what about decaf itself?

**Comment by neobrain** [comment]
Yeah, no.

**Comment by logos88** [comment]
I also believe merging to Dolphin would be a great idea. It would bring a big community of people to help and improve the emulator in a greater speed. Otherwise it looks like CEMU, despite being closed, will be the Wii U emulator of reference in the future I fear.

**Comment by TechnoCrunch** [comment]
Like neobrain said, no. decaf-emu and Dolphin code bases are too different to even begin to merge. Also I think decaf-emu will be the Wii U emulator for the future, like everything it just requires a jumpstart for it to speed up.

**Comment by MoochMcGee** [comment]
Are you people stupid? The Wii U is emulated in a COMPLETELY DIFFERENT WAY
from the Wii. With the Wii, you gotta actually emulate the hardware. With
the Wii U, emulating the OS is sufficient.

**Comment by brett19** [comment]
@MoochMcGee You're being unnecessarily rude, please keep things civilized here...

P.S. You're not even correct.  Whilst the Dolphin and Decaf emulators are indeed substantially different, and the effort to merge them would be enormous, that doesn't mean that it couldn't happen.  Though we currently do HLE in Decaf, there are reasons that LLE could become useful, and then the balance between simplicity and sharing code with Dolphin would change.
