### ISSUE TITLE
Bailing on JIT 0800001

### ISSUE THREAD

**Issue by fuhuan416** [decaf-emu/decaf-emu#144]
When i boot Super Mario Make, then appear these information.
C:\Users\Harder\Desktop\Decaf-20160528-x64>decaf play --jit c:\download\smm\code
[info:FFFF] Using GLFW
[warning:FFFF] Could not open /vol/code/cos.xml, using default values
[warning:FFFF] Could not open /vol/code/app.xml, using default values
[info:FFFF] Loaded module gameloader.rpl
[info:FFFF] Loaded module coreinit.rpl
[warning:0101] Bailing on JIT 08000001 ident due to failed decode at 08000001

Decaf window nothind to show, it's blank.

**Comment by exjam** [comment]
This has been fixed in 28bd0dc91c6d73e8a8aea94c5c7a1fd524d4a90a
