### ISSUE TITLE
Recreate shaders when any register used to generate them has been modified.

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#163]
Currently we only check the base address of the shader program as an index into the generated shader map - this is incorrect.

Multiple registers are used in shader creation and all of these must be identical in order for us to reuse the same generated OpenGL shader, for example use of SX_ALPHA_TEST_CONTROL.

**Comment by brett19** [comment]
To be fair, this should be more than likely an assertion, not a recreation.  A single shader address with a certain bytecode should not work except with a single set of register values (ie: A shader set up for a sampler2D won't work properly with a sampler3D).
