### ISSUE TITLE
Wrong alignment for compressed textures

### ISSUE THREAD

**Issue by achurch** [decaf-emu/decaf-emu#176]
addrlib seems to return the wrong alignment for compressed texture formats -- for example, 8192 bytes for BC3 when it should apparently be 4096 (Xenoblade loads some BC3 textures at address 0x....N000 with odd N). A trivial hack which at least fixes Xenoblade textures is to just halve the alignment returned by addrlib for those types (see achurch@7389ddb); this is presumably not the proper fix, but I haven't dug into addrlib far enough to figure out where the problem is, or whether it's a bug in addrlib itself or a bug in how decaf uses it. Putting this up in case anyone else has ideas.

**Comment by brett19** [comment]
Textures are meant to be aligned to 8096 in general, however an offset of 4096 is actually a special alignment which is used to tell the GPU that there is another kind of bank swizzle mode activated (if I remember correctly).

**Comment by achurch** [comment]
In one particular case I looked at, XB was loading a resource file of size 0x4000 to a 0x4000-aligned offset, and the BC3 texture data was at offset 0x1000 in that file (thus loaded at address 0x..5000), so I'm pretty sure real hardware uses an alignment of 0x1000 (4096) for at least that case.

**Comment by achurch** [comment]
Fixed by 97a259e.
