### ISSUE TITLE
just a question...

### ISSUE THREAD

**Issue by Gamedev1909** [decaf-emu/decaf-emu#199]
any chance of getting a ui soon ?

**Comment by MoochMcGee** [comment]
where's the question, lol?

**Comment by Gamedev1909** [comment]
when can we get a ui

**Comment by exjam** [comment]
I do not feel a need for a UI until the emulator itself is in a more usable state. Right now the project is not intended for the average end user, and it is plenty easy enough for a developer to edit the json config file.

However, I would be willing to accept a pull request for a Qt based UI. We would continue to maintain decaf-cli and decaf-sdl though, as not everyone would like a dependency on something as large as Qt.
