### ISSUE TITLE
Refactor loader's elf handling to use be_val

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#222]
Currently the loaders ELF structures are all in little-endian, and then they have a set of functions used for reading them along with a 'BigEndianView'.  This view is only used for elf files now as we use be_val to wrap all big-endian data.  The ELF structures should be refactored to use be_val values, and then the reader functions can be removed (along with the BigEndianView).

**Comment by exjam** [comment]
022f7a8d479e5f5577f27bce8bc66320c3be637a
