### ISSUE TITLE
Implement or stub H264 decoding functions

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#229]
We either want to implement h264 decoding (which would take a reasonable amount of effort to do), or for now we can stub functions to fake playback in order to get games to continue.

Tank tank tank! will infinitely call H264DECFindDecstartpoint as it is trying to find the decoding start point.

```
[info:w108] Unimplemented kernel function h264.rpl::H264DECMemoryRequirement called from 0x02071640
[info:w108] Unimplemented kernel function h264.rpl::H264DECCheckMemSegmentation called from 0x0207165C
[info:w108] Unimplemented kernel function h264.rpl::H264DECCheckMemSegmentation called from 0x02071684
[info:w108] Unimplemented kernel function h264.rpl::H264DECInitParam called from 0x020716A0
[info:w108] Unimplemented kernel function h264.rpl::H264DECSetParam called from 0x020716B4
[info:w108] Unimplemented kernel function h264.rpl::H264DECSetParam called from 0x020716BC
[info:w108] Unimplemented kernel function h264.rpl::H264DECOpen called from 0x020716C4
[info:w108] Unimplemented kernel function h264.rpl::H264DECBegin called from 0x020717D0
[info:w108] Unimplemented kernel function h264.rpl::H264DECFindDecstartpoint called from 0x020717F0
[info:w108] Unimplemented kernel function h264.rpl::H264DECFindDecstartpoint called from 0x020717F0
[info:w108] Unimplemented kernel function h264.rpl::H264DECFindDecstartpoint called from 0x020717F0
[info:w108] Unimplemented kernel function h264.rpl::H264DECFindDecstartpoint called from 0x020717F0
[info:w108] Unimplemented kernel function h264.rpl::H264DECFindDecstartpoint called from 0x020717F0
....
```

In case someone wanted to actually implement h264 decoding, the full list of H264.rpl functions that Tank Tank Tank! imports is:

```
h264.rpl::H264DECBegin
h264.rpl::H264DECCheckDecunitLength
h264.rpl::H264DECCheckMemSegmentation
h264.rpl::H264DECClose
h264.rpl::H264DECEnd
h264.rpl::H264DECExecute
h264.rpl::H264DECFindDecstartpoint
h264.rpl::H264DECFindIdrpoint
h264.rpl::H264DECGetImageSize
h264.rpl::H264DECInitParam
h264.rpl::H264DECMemoryRequirement
h264.rpl::H264DECOpen
h264.rpl::H264DECSetBitstream
h264.rpl::H264DECSetParam
```

**Comment by exjam** [comment]
For a full list of exports from h264.rpl see:
https://github.com/decaf-emu/decaf-emu/wiki/h264.rpl

**Comment by tykel** [comment]
Taking a look into this, already getting to TANK TANK TANK!'s main menu with mostly shims.

**Comment by ttay24** [comment]
is there a good way/process to find out the parameters for these functions?

**Comment by exjam** [comment]
Reversing from h264.rpl or games which use h264.rpl is the only way to do it, there are IDA RPL/RPX loader plugins available if you use IDA.

**Comment by godofgrunts** [comment]
IDA is extremely expensive... Is there an open source decompiler that works?

**Comment by exjam** [comment]
Only if someone writes a loader for them... Good luck finding a PowerPC disassembler which even comes close to as being as good as IDA though!

**Comment by Sammi-Husky** [comment]
Iirc you should also be able to use rpl2elf then load the resulting elf in any dissassembler you like, provided it supports the architecture. But yea nothing i've used in the past can even come close to IDA, and with them coming out with HexRays decompiler support for PPC the draw to it is even greater

**Comment by Gamedev1909** [comment]
i have ida 6.8 pro and a rpx decompiler for itif anyone wants to use it ask
