### ISSUE TITLE
Failed building on Debian 8 with clang 3.8

### ISSUE THREAD

**Issue by ProfessorKaos64** [decaf-emu/decaf-emu#241]
Using pretty standard build instructions given, sourcing packages from the Travis file.

```
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1915 (message):
  No download info given for 'asmjit' and its source directory:

   /build/decaf-0.20160803+git+bsos/libraries/asmjit

  is not an existing non-empty directory.  Please specify one of:

   * SOURCE_DIR with an existing non-empty directory
   * URL
   * GIT_REPOSITORY
   * HG_REPOSITORY
   * CVS_REPOSITORY and CVS_MODULE
   * SVN_REVISION
   * DOWNLOAD_COMMAND
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  CMakeLists.txt:48 (externalproject_add)
```

Log: http://slexy.org/view/s23vvdPUK7

**Comment by exjam** [comment]
Sounds like you are missing a `git submodule update --init`

**Comment by ProfessorKaos64** [comment]
Doh...will try that soon. If that's it, I apologize for the preemptive issue ticket.

**Comment by ProfessorKaos64** [comment]
I actually still get some errors late into the build. Log: http://sprunge.us/SWJC

**Comment by exjam** [comment]
That's weird, is_trivially_copyable should be from <type_traits> which that file includes.

We are already setting -std=c++14:
https://github.com/decaf-emu/decaf-emu/blob/master/CMakeLists.txt#L90-L91

Maybe you have an old compiler without support for is_trivially_copyable?

**Comment by ProfessorKaos64** [comment]
That's why I am using clang backported from Debian Stretch. I'll check into this more. Wonder if I have to set CC or CXX explicitly, but it is picked up by CMake just fine. hmm....

**Comment by ProfessorKaos64** [comment]
Seems GCC > 5 (as expected) [can handle](http://stackoverflow.com/questions/25123458/is-trivially-copyable-is-not-a-member-of-std) those instructions. Maybe clang cannot. Still looking. Have you tried using clang with your travis build / manually?

**Comment by achurch** [comment]
FYI, I build with Clang 3.8 (Gentoo Linux) and don't get any errors about is_trivially_copyable. I'm using libc++ instead of GNU libstdc++, though, which may have something to do with it (I forget the original error which prompted me to use libc++).

**Comment by ProfessorKaos64** [comment]
Interesting. I'll give that a try. I backports llvm-3.9 for fun anyway  :)

**Comment by achurch** [comment]
If it is a libstdc++/libc++ issue, it's probably just that libstdc++ is written to be used with GCC and it has some idiosyncrasy which causes Clang to fail.

**Comment by ProfessorKaos64** [comment]
```
The following type trait primitives are supported by Clang:

__has_nothrow_assign (GNU, Microsoft)
__has_nothrow_copy (GNU, Microsoft)
__has_nothrow_constructor (GNU, Microsoft)
__has_trivial_assign (GNU, Microsoft)
__has_trivial_copy (GNU, Microsoft)
```

Reading to see if I can specify clang use this vs. GNU c++

**Comment by ProfessorKaos64** [comment]
In reading the language manual for clang, I am seeing what you describe. Any way you know I can force usage of libc++? Still parsing this

**Comment by achurch** [comment]
FYI, here's the script I use to configure a new build directory:
```
#!/bin/sh
cmake "$(dirname "$0")" \
    -DDECAF_VALGRIND=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_CXX_FLAGS="-O2 -g -stdlib=libc++"
```

**Comment by ProfessorKaos64** [comment]
``
-stdlib=libc++"
``

THAT was what i was looking for. Thank you very much. I am trying to find a list of those -std standard flags. Any resource / manual link I can note down?

**Comment by achurch** [comment]
None that I know of, I'm afraid -- I just found -stdlib= after random Googling.

**Comment by ProfessorKaos64** [comment]
Got a bit further this time: http://sprunge.us/dbNA

**Comment by ProfessorKaos64** [comment]
Got a bit further: http://sprunge.us/Jihg

**Comment by exjam** [comment]
Can you please look at your logs before posting them here, we get emails every time you comment on this issue - it is not our responsibility to fix your environment.

I don't mind helping with some issues but this one you could have solved yourself if you just press ctrl+f and looked for "error:"

`/tmp/buildd/decaf-0.20160805+git+bsos/src/common/src/platform_posix_fiber.cpp:12:13: fatal error: 'valgrind/valgrind.h' file not found`

Here you can see you are missing valgrind.h, so either don't use -DDECAF_VALGRIND=ON  or download the valgrind dev package for your platform.
