### ISSUE TITLE
Update glbinding

### ISSUE THREAD

**Issue by achurch** [decaf-emu/decaf-emu#253]
I thought I had mentioned this somewhere, but in case not, there's a race condition in glbinding which, at least on my machine, causes moderately frequent crashes on startup. I submitted a fix at https://github.com/cginternals/glbinding/commit/314f4c0233eb75adeb2cd2858e49da9f01f1ad3d, so you should probably look into updating the library at some point. (There have apparently been some API changes in the interim, as when I tried to update it myself I got build errors, and I haven't had time to look into it more deeply.)

**Comment by exjam** [comment]
a239eae56cfaf1cab808152573f92b5a8ffe9429
