### ISSUE TITLE
layout qualifier 'xfb_stride' conflicts with previous declaration

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#284]
0(42) : error C7605: layout qualifier 'xfb_stride' conflicts with previous declaration

```
layout(xfb_buffer = 0, xfb_stride = 4) out block {
   layout(xfb_offset = 0) out float feedback_0_0;
};
layout(xfb_buffer = 1, xfb_stride = 12) out block {
   layout(xfb_offset = 0) out vec3 feedback_1_0;
};
layout(xfb_buffer = 2, xfb_stride = 12) out block {       <---- this is line 42 btw
   layout(xfb_offset = 0) out vec3 feedback_2_0;
};
layout(xfb_buffer = 3, xfb_stride = 12) out block {
   layout(xfb_offset = 0) out vec3 feedback_3_0;
};
```

Any ideas @achurch  ?

There are no other errors if i remove xfb_stride from the declaration, and it handles the first two blocks perfectly fine - this error doesn't make much sense and I can't find anything on google about it... possible driver bug? I also tried using "block0, block1, block2, block3" because i saw that in the ARB enhanced_layouts spec, but still same error message!

**Comment by achurch** [comment]
That's bizarre - yeah, could be a driver bug. Can you post the full shader? I'll mess around a bit and see if I can reproduce it / find the cause.

**Comment by brett19** [comment]
Hey @achurch,
You should be able to easily reproduce this just by attempting to compile a shader with the above information.  Hit me up on IRC for some more details.

**Comment by achurch** [comment]
I think you got the line with the error wrong -- I reproduced the issue, but the error was on the closing brace of the second block, not the beginning of the third block. Looking more closely at the GLSL spec, it seems it wants an actual block name (not a "block" keyword") there, so I'll send a PR to fix that. That said, I do still get the "stride mismatch" error with unique block names, so not sure what the root cause is.

**Comment by exjam** [comment]
For reference here was the shader I had the problem with: https://gist.github.com/exjam/2c00a6f638301a9f7d64ce5e82863383

**Comment by achurch** [comment]
Yeah, I don't see anything wrong with that translation. Can you try this and see if it helps: https://github.com/achurch/decaf-emu/commit/025d7e37906c1d1615dc6a9c78255e84dc526500

Feel free to merge it in if it works. It shouldn't have any performance impact other than a negligible GLSL parsing cost at shader compilation time.

**Comment by exjam** [comment]
Yeah this seems to resolve the issue!
