### ISSUE TITLE
Stepping in the debugger doesn't work with JIT

### ISSUE THREAD

**Issue by achurch** [decaf-emu/decaf-emu#288]
I haven't fully tracked down the cause, but it looks like JIT code doesn't return back as far as cpu::resume() after being stopped, so the breakpoint on the next instruction isn't seen.

**Comment by brett19** [comment]
Yea... We need to implement JIT cache management and then implement breakpoints using actual int3 instructions inserted into the instruction stream for JIT.  This would be far faster and a lot safer.

**Comment by exjam** [comment]
This was fixed a while ago.
