### ISSUE TITLE
Find alternatives for the fonts used by OSGetSharedData

### ISSUE THREAD

**Issue by zhuowei** [decaf-emu/decaf-emu#29]
Many applications (such as Mii Maker) use the four shared TTF fonts (CafeCn.ttf, CafeKr.ttf, CafeStd.ttf, CafeTw.ttf) obtained from OSGetSharedData, and crash if no font is present. I don't think these fonts can be redistributed with the emulator.

Do we ship alternative fonts with the emu, or could we fall back to any TTF font (e.g. Arial on Windows)?

**Comment by exjam** [comment]
A quick google says the Wii U system font is Albany Std Regular but that isn't a free font either :).

We probably want something with similar sizes and spacing otherwise I'm sure some texts will not fit properly.

**Comment by ohnozen** [comment]
Looks very similar to Adobe's [Source Sans](https://www.google.com/fonts/specimen/Source+Sans+Pro).

Quick glance: The caps in Albany look slighty wider. SS might be slightly narrower overall.

**Comment by exjam** [comment]
We ended up using Source Sans for now. Thanks ohnozen.

8c9d064564594495613d367b4933128f70cc98c7

**Comment by rajkosto** [comment]
Hello. Source sans is a tiny font while the original fonts are all CJK fonts, each supporting one asian language. I have converted Noto Sans CJK fonts from PostScript outlines to TrueType outlines (required for them to be rendered properly inside wiiu), and then recreated the glyphs from the E000-E099 private range which some games use for controller buttons, etc (nintendos: https://images.sshnuke.net/2017-07-13_10-31-52.png, mine: https://images.sshnuke.net/2017-07-13_10-31-37.png) using only PUBLIC DOMAIN resources and my own drawings.

You can get the fonts here: https://files.sshnuke.net/sharedFonts.7z
