### ISSUE TITLE
compile issue on Ubuntu 14.04 x64 - platform_win_stacktrace.cpp:3:28: fatal error: spdlog/fmt/fmt.h

### ISSUE THREAD

**Issue by rcampbel3** [decaf-emu/decaf-emu#298]
updated to 8/16 source
did a git pull and then the following:

rcampbel@rcampbel-OptiPlex-745~/project/decaf-emu $ git submodule update --init
error: no such remote ref 4fcde3b8508364deb4321baba6fef02cc3b59a44
Fetched in submodule path 'libraries/spdlog', but it did not contain 4fcde3b8508364deb4321baba6fef02cc3b59a44. Direct fetching of that commit failed.
rcampbel@rcampbel-OptiPlex-745~/project/decaf-emu $ make clean
rcampbel@rcampbel-OptiPlex-745~/project/decaf-emu $ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rcampbel/project/decaf-emu
rcampbel@rcampbel-OptiPlex-745~/project/decaf-emu $ make
[ 39%] Building CXX object CMakeFiles/imgui.dir/libraries/imgui/imgui.cpp.o
[ 39%] Building CXX object CMakeFiles/imgui.dir/libraries/imgui/imgui_draw.cpp.o
[ 39%] Linking CXX static library libimgui.a
[ 39%] Built target imgui
[ 39%] Building CXX object CMakeFiles/addrlib.dir/libraries/addrlib/src/addrinterface.cpp.o
[ 39%] Building CXX object CMakeFiles/addrlib.dir/libraries/addrlib/src/core/addrelemlib.cpp.o
[ 39%] Building CXX object CMakeFiles/addrlib.dir/libraries/addrlib/src/core/addrlib.cpp.o
[ 39%] Building CXX object CMakeFiles/addrlib.dir/libraries/addrlib/src/core/addrobject.cpp.o
[ 39%] Building CXX object CMakeFiles/addrlib.dir/libraries/addrlib/src/r600/r600addrlib.cpp.o
[ 39%] Linking CXX static library libaddrlib.a
[ 39%] Built target addrlib
[ 39%] Building CXX object CMakeFiles/pugixml.dir/libraries/pugixml/src/pugixml.cpp.o
[ 39%] Linking CXX static library libpugixml.a
[ 39%] Built target pugixml
[ 39%] Creating directories for 'glbinding'
[ 39%] No download step for 'glbinding'
[ 39%] No patch step for 'glbinding'
[ 39%] No update step for 'glbinding'
[ 39%] Performing configure step for 'glbinding'
loading initial cache file /home/rcampbel/project/decaf-emu/glbinding-prefix/tmp/glbinding-cache-.cmake
-- gitdir: ../../.git/modules/libraries/glbinding
-- ../../.git/modules/libraries/glbinding
-- /home/rcampbel/project/decaf-emu/libraries/glbinding/../../.git/modules/libraries/glbinding
-- Lib glbinding
-- Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR)
Tool glcontexts skipped: GLFW not found
-- Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR)
Tool glfunctions skipped: GLFW not found
-- Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR)
Tool glmeta skipped: GLFW not found
-- Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR)
Tool glqueries skipped: GLFW not found
-- Command update
-- Command generate
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rcampbel/project/decaf-emu/glbinding-prefix/src/glbinding-build
[ 39%] Performing build step for 'glbinding'
[100%] Built target glbinding
[ 39%] No install step for 'glbinding'
[ 39%] Completed 'glbinding'
[ 39%] Built target glbinding
[ 39%] Creating directories for 'asmjit'
[ 39%] No download step for 'asmjit'
[ 39%] No patch step for 'asmjit'
[ 39%] No update step for 'asmjit'
[ 39%] Performing configure step for 'asmjit'
loading initial cache file /home/rcampbel/project/decaf-emu/asmjit-prefix/tmp/asmjit-cache-.cmake
-- [asmjit] Standalone | Mode=Static | Test=Off
-- [asmjit] ASMJIT_DIR=/home/rcampbel/project/decaf-emu/libraries/asmjit
-- [asmjit] ASMJIT_DEPS=pthread;rt
-- [asmjit] ASMJIT_LIBS=asmjit;pthread;rt
-- [asmjit] ASMJIT_CFLAGS=
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rcampbel/project/decaf-emu/asmjit-prefix/src/asmjit-build
[ 39%] Performing build step for 'asmjit'
[100%] Built target asmjit
[ 39%] No install step for 'asmjit'
[ 39%] Completed 'asmjit'
[ 39%] Built target asmjit
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/assert.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/murmur3.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_posix_dir.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_posix_exception.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_posix_fiber.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_posix_memory.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_posix_stacktrace.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_posix_thread.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_posix_time.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_win_dir.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_win_exception.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_win_fiber.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_win_memory.cpp.o
[ 39%] Building CXX object src/common/CMakeFiles/common.dir/src/platform_win_stacktrace.cpp.o
/home/rcampbel/project/decaf-emu/src/common/src/platform_win_stacktrace.cpp:3:28: fatal error: spdlog/fmt/fmt.h: No such file or directory
compilation terminated.

**Comment by brett19** [comment]
Something has gone wrong with your submodule checkout.  It builds fine for me, both on the currently submoduled spdlog, as well as using master.

**Comment by exjam** [comment]
Hi @rcampbel3 , this is because the remote of spdlog has changed.

1. vim .git/config
2. change url = exjam/spdlog to gabime/spdlog
3. rm -rf .git/modules/libraries/spdlog/
4. rm -rf libraries/spdlog/
5. git submodule update --init

or just delete your whole decaf-emu and clone again.
