### ISSUE TITLE
Change --log-file to allow specifying the log filename.

### ISSUE THREAD

**Issue by ttay24** [decaf-emu/decaf-emu#311]
So, I've looked at the log options and I'm not sure if it's brokey broke or if i'm doing it wrong.

I've tried the following:
> --log-file "logs/log.txt"
> --log-file "logs/"

But neither seem to redirect any of the logs (the main log or the log for a game). Any guidance here?

**Comment by exjam** [comment]
Unfortunately the --log-file argument is a bit misleading here, we should probably change it.

Currently --log-file just enables logging to file, rather than specifying a path for the file.

https://github.com/decaf-emu/decaf-emu/blob/master/src/decaf-sdl/main.cpp#L165-L167

**Comment by ttay24** [comment]
Ah, I see.

So would we want this to be split into two args? One for logging on/off, and another to specify a directory? Would the directory be used for the main log file and any log files for games?

**Comment by exjam** [comment]
2d1252db53fd23f0adbb3526463250194c25c69e
