### ISSUE TITLE
Avoid unnecessary copies between colocated textures and colorbuffers

### ISSUE THREAD

**Issue by achurch** [decaf-emu/decaf-emu#315]
When a game has a framebuffer which is alternately used as texture and framebuffer, and the sizes don't match but the layout is compatible (e.g. non-tile-aligned texture size rounded up to aligned framebuffer size), we currently do a host surface copy on every framebuffer/texture usage switch. The texture->framebuffer copy isn't necessary if the texture hasn't been dirtied from the CPU side, and the framebuffer->texture copy isn't necessary if the framebuffer was write-masked on every draw call while it was bound. This can potentially save a lot of GPU-side surface copying, e.g. in Xenoblade which shuffles around lots of intermediate framebuffers.

**Comment by exjam** [comment]
This is handled in the new Vulkan backend.
