### ISSUE TITLE
Handle non-shadow sampling from depth textures.

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#321]
I believe we need to use GL_DEPTH_TEXTURE_MODE.  The specific shader I saw was reading the data out of `.a` (which 'conveniently' has a GL equivalent through DEPTH_TEXTURE_MODE), with DEPTH_24_8.

**Comment by mudlord** [comment]
Yah, use:
glTexParameteri (GL_TEXTURE_2D, GL_TEXTURE_COMPARE_MODE, GL_NONE);
glTexParameteri (GL_TEXTURE_2D, GL_DEPTH_TEXTURE_MODE, GL_INTENSITY);   

Should be able then to read the depth texture then.

**Comment by brett19** [comment]
This should allow us to drop texture duplication for depth texture reading.  We should be able to turn off depth comparisons and enable DEPTH_TEXTURE_MODE as alpha (this appears to be what games are more or less doing).

**Comment by mudlord** [comment]
I thought depth_texture_mode was deprecated?

**Comment by brett19** [comment]
This is no longer valid with Vulkan, which requires different methods and I believe they are already implemented.
