### ISSUE TITLE
Implement Geometry Shaders

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [decaf-emu/decaf-emu#323]
[dktf_2016-08-19_13-35.txt](https://github.com/decaf-emu/decaf-emu/files/427461/dktf_2016-08-19_13-35.txt)

**Comment by exjam** [comment]
This is because we have not yet implemented geometry shaders. Also that's a funny looking stack trace, the stack trace printed must be broken in some way!

**Comment by Gamedev1909** [comment]
hey thanks

**Comment by exjam** [comment]
This is implemented in the new Vulkan backend, although maybe not merged to master yet.
