### ISSUE TITLE
Stipulations and obligations of future of decaf emulator

### ISSUE THREAD

**Issue by RobStevenson63** [decaf-emu/decaf-emu#328]
To Andrew Churche, Brett Lawson, James Brenton:

With respect to the Cemu Wii U Emulator for Windows (herein referred to as "Cemu"), these stipulations promote 
better respect for Cemu and the intellectual property rights of its respective rights holder.

1. Decaf-emu will seek not to implement any feature that Cemu has recently implemented.
   A period of six ("6") months shall be observed before Decaf-emu implements said feature, unless permission can 
be obtained from the project maintainer of Cemu.

2. Decaf-emu will share any and all monetary donations with the Cemu project at a rate agreed upon by the project 
maintainer of Cemu. 

3. Decaf-emu will endeavour to embargo any commits that increase compatibiltiy beyond that of Cemu, and will 
reverse any previous commits that have already done so.

4. Decaf-emu will endeavour to discourage users from promoting Decaf-emu on the same social media websites and 
services that Cemu is also promoted on.

5. Decaf-emu will endeavour to credit Cemu in any and all future release notes and it's project maintainer, Exzcap.

6. Decaf-emu will make its source code repository private and not available for public use.

7. Decaf-emu will not release any new versions until six ("6") weeks after Cemu has released a new version.

8. Decaf-emu's maintainers and contributors will endeavour to be respectful to Cemu's project maintainer and will 
discourage denigration of Cemu. 

These stipulations are to be adhered to from 1 September, 2016 at 12:01AM UTC until which time the Cemu project has 
been officially discontinued or the project maintainer of the Cemu project authorizes the release from the 
stipulations. 

It will be assumed that the above named maintainers and contributors of Decaf-emu will adhere to these stipulations 
in good faith. 

Signed,

The GBATemp Intellectual Property Defense of Cemu Concerned Citizens Committee
Emulator Development Fund International
Committee To Protect Software Developers Nederland
Deutsche Zunderkraftun GmbH
Ireland Computer Sciences Development Fund
Michael Hansen: Concerned user
Robert Stevenson: Concerned user
Anonymous individual: Concerned user

CODE:Attachment
C:\\Users\\Rob\\Desktop\\committeesignature.jpeg
//CODE

Citations:
United Nations Security Council Resolution 19983
North Atlantic Free Trade Agreement, Section H
European Union Charter of Human Rights

**Comment by mabbas64** [comment]
We can agree to these terms when Cemu becomes open source and merges into decaf.

Signed,
The caretaker humanitarian fan club of decaf-emu

**Comment by Adubbz** [comment]
This is the best shit I've read in a long time. Nice job. :baby_bottle: :baby: :laughing:

**Comment by brett19** [comment]
I'm just going to go ahead and leave this open.

**Comment by Sans0Serif** [comment]
kek <--- this one
kek
kek
kek

**Comment by SakataGintokiYT** [comment]
LOL
- Decaf emulator is better :)  👍

**Comment by emmauss** [comment]
it this for real, cause this is the best definition of bullshit.

**Comment by CreeperMario** [comment]
1. I really don't think Exzap cares too much about Decaf, they are both separate projects created by separate teams, advancing at separate rates.
2. What donations? As far as I'm aware, the Decaf team is not currently asking for donations.
3. Reversing commits on GitHub is messy, and I know from first hand experience.
4. The Decaf team has the rights to promote their project, they own it, it is not related to Cemu.
5. What did Exzap do for Cemu? If you're talking about @exjam they are separate people.
6. The Decaf team has the rights to do whatever they want with their code, they can make it open-source if they choose to.
7. That would mean that new releases of Decaf would be impossible, as Cemu has a new release every three weeks, longer than your so-called six week grace period.
8. Neither of these projects are affiliated with each other, the teams have the same amount of respect for each other as I have with people like @vgmoose @xhp-creations @pwsincd @QuarkTheAwesome and many others.
9. Stop trying to discourage people from making awesome content, you troll.
10. GitHub needs a banhammer feature. '+1' if you agree.

**Comment by exjam** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Gamedev1909** [comment]
github has a ban hammer feature but it's only local to the hub you ban in

**Comment by GoldtexTwitch** [comment]
fucking priceless

**Comment by Helios747** [comment]
lmao

**Comment by Whovian9369** [comment]
That is amazingly funny. Good luck enforcing this.

**Comment by JMC47** [comment]
My question is why hasn't this issue been marked as accepted.

**Comment by Margen67** [comment]
Don't forget that if it's open source people will add online support just to cheat.
Now online is **ruined** thanks to the decaf devs.
Also since it's open source the code will become messy because you have to accept all pull requests.
Then someone will steal it and make money off of it.

This is why you go closed source. /s
