### ISSUE TITLE
Several games have a broken alpha on textures

### ISSUE THREAD

**Issue by JohnGodgames** [decaf-emu/decaf-emu#331]
There are plenty of games with a broken alpha caused by https://github.com/decaf-emu/decaf-emu/pull/314

![ice](https://cloud.githubusercontent.com/assets/11453507/17830989/cab73c56-66dd-11e6-956e-54dae03cc3e5.PNG)

There is a **[video](https://www.youtube.com/watch?v=vnfM4nBtqN0)** of some 

@achurch ping?

LOG - http://pasted.co/1ebb8a2a

**Edit:**
I found that it comes from https://github.com/decaf-emu/decaf-emu/pull/314/commits/9cefb15af1f8a73825b63deae57942ca2a3697bf

and after revert it's ok again 

![ice 2](https://cloud.githubusercontent.com/assets/11453507/17831091/54096ac2-66e0-11e6-8a33-6d0b2e8853a0.PNG)

**Comment by achurch** [comment]
Do you see in the log any messages saying "Depth export is masked by db_shader_control"?

**Comment by JohnGodgames** [comment]
I've added a log, but "Depth export is masked by db_shader_control" isn't there.

**Comment by achurch** [comment]
That error is unrelated to the change you indicated, so if that's the immediate cause of the bug, the root cause lies in another change.

As an experiment, you can try commenting out this line:
```
out << "layout(early_fragment_tests) in;\n";
```
If that makes the problem go away, it may mean there's a GL driver issue that needs to be taken into account.

**Comment by JohnGodgames** [comment]
Yeah issue is gone after commenting out that line.

**Comment by achurch** [comment]
Oh, I think I see the problem -- early fragment tests need to take into account whether the fragment shader uses the discard instruction.

The easy solution is to just remove that line. A better solution is to record whether the shader uses the discard instruction and disable early fragment tests in that case (theoretically the KILL_ENABLE bit indicates this, but a shader could have KILL_ENABLE set and still never use discard). I'll look into doing that.

**Comment by achurch** [comment]
Can you please try: https://github.com/achurch/decaf-emu/commit/32329b725522a72d8a8df1f8db007e96a6a06b6c

**Comment by JohnGodgames** [comment]
Yeah it looks good.Tried 3 games with that...
