### ISSUE TITLE
Any invalid argument/option causes fatal error

### ISSUE THREAD

**Issue by ttay24** [decaf-emu/decaf-emu#338]
When starting decaf-sdl with an invalid argument, it "stops working" without any error output. Not sure if this is expected, but I would think the invalid parameter should be printed to the screen and the legit options should be shown.

> decaf-sdl play --jit "some_game" --log-file --test

**Comment by exjam** [comment]
I actually fixed this like a month ago but I forgot to update the submodule... oops
