### ISSUE TITLE
MEGA_FETCH misshandling

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#340]
Currently I believe there is some places that we assume MEGA/MINI fetching controls the size of the data that is being retreived.  It appears to actually only be a cache hint.  I'm looking at a shader that does a FETCH with MEGA(32) for a 16-byte read, then the next FETCH uses MINI(16).

It seems that MEGA means to fetch directly the requested data in one burst, and then a MINI says to try to retrieve from the cache and fall back to MEGA with the indicated size only if needed.

```
FETCH   R1.xyzw, R0.x, b159 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(48)
FETCH   R2.xyzw, R0.x, b159 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(32) OFFSET(0)
FETCH   R3.xyzw, R0.x, b159 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MINI(16) OFFSET(16)
FETCH   R4.xyzw, R0.x, b159 NO_INDEX_OFFSET FMT_FROM_FETCH_CONSTANT MEGA(16) OFFSET(32)
```

**Comment by exjam** [comment]
This is handled in Vulkan backend.
