### ISSUE TITLE
EVENT_WRITE saves its EOP write instead of executing it

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#341]
I saw this when reading through #334 and some others.  We currently store the EVENT_WRITE's into an mPendingEOP location.  We should not be doing this, and instead be executing the EVENT_WRITE immediately.  When the documentation refers to End-Of-Pipeline (EOP), what it's actually referring to is its internal instruction pipeline.  This is relevant to the GPU because they need to ensure that the write only occurs AFTER the pipeline is empty of all operations that came before the EVENT_WRITE.  In the case of our command execution, we do not have a pipeline and only need to do the write immediately (or once we have our async pipeline, do it async based on a fence).

**Comment by achurch** [comment]
Happened to be working near this code, so here you go: https://github.com/achurch/decaf-emu/commit/e2c88a79b47c24ae5cf9ab09094a071287ea59c2

**Comment by brett19** [comment]
@achurch Looks good, can you PR this?

**Comment by achurch** [comment]
Done, #350.
