### ISSUE TITLE
Should CB_BLEND_{RED,...} divide by 255?

### ISSUE THREAD

**Issue by achurch** [decaf-emu/decaf-emu#342]
Currently, the GL handlers for writes to `CB_BLEND_{RED,GREEN,BLUE,ALPHA}` divide the register values by 255. This seems odd since the registers are already floating-point, and (at least in the decaf implementation) GX2SetBlendConstantColor() sends its float arguments directly to the registers without any sort of multiplication. I don't have a test case, but maybe someone can look into this and see whether the current code is correct or not?

**Comment by exjam** [comment]
No it definitely should not. Good catch.

[36:16.018706 debug:w108] 0x02001088 GX2SetBlendConstantColor(1, 0.5, 0.3, 0.2)
