### ISSUE TITLE
Ittle Dew - Graphical bugs (trace included)

### ISSUE THREAD

**Issue by JohnGodgames** [decaf-emu/decaf-emu#352]
It's unplayable due to almost black screen

![ittle](https://cloud.githubusercontent.com/assets/11453507/17898029/9194f8ac-6956-11e6-8b64-f451b31b30f9.PNG)

[Reference video](https://www.youtube.com/watch?v=m7YC3wBQRNk)

**[LOG](http://pasted.co/b56adf63)**

**[TRACE DOWNLOAD (apitrace)](https://mega.nz/#!iUsRCSwK!yq_N77FBe04Mpzc5ReCayZvVJ2HfNCqpcReLa0zG6fQ)**

**Comment by brett19** [comment]
Closing this as it predates the Vulkan backend which likely doesn't exhibit this issue.
