### ISSUE TITLE
assertion failed ( coreinit_thread.cpp) 

### ISSUE THREAD

**Issue by ankoku66** [decaf-emu/decaf-emu#354]
log-
Expression: internal::isThreadActiveNoLock(thread)
File: ..\src\libdecaf\src\modules\coreinit\coreinit_thread.cpp
Line: 473
Stacktrace:
7: SDL_SetClipboardText - 0x7FF772995100x
-

**Comment by JohnGodgames** [comment]
Yeah @brett19 already know about it.Caused by https://github.com/decaf-emu/decaf-emu/commit/cb3153659cea01e58083d01ac462be62a02e5405

**Comment by brett19** [comment]
Fixed in 0fc6b154
