### ISSUE TITLE
Ben 10 Omniverse games - Regression (GX2SetDRCConnectCallback)

### ISSUE THREAD

**Issue by JohnGodgames** [decaf-emu/decaf-emu#357]
There is a oldy regression which is caused by 8ba914b ("gx2: Implement GX2SetDRCConnectCallback.", 2016-08-15)

**Ben 10: Omniverse (a0b3dbe)**
![ben 10 ok](https://cloud.githubusercontent.com/assets/11453507/17912801/518fb9f0-6996-11e6-9a1f-f93d2eb80c64.gif)

**Ben 10: Omniverse (8ba914b)**
Immediately crash

**Ben 10: Omniverse 2 (a0b3dbe)**
![ben 10 2 ok](https://cloud.githubusercontent.com/assets/11453507/17912783/302bd1d6-6996-11e6-8569-f4606ac2fcaf.gif)

**Ben 10: Omniverse 2 (8ba914b)**
![ben 10 2 nok](https://cloud.githubusercontent.com/assets/11453507/17912813/66c6e104-6996-11e6-9c0b-d1e11a156650.gif)

**Comment by exjam** [comment]
This is fixed now.
