### ISSUE TITLE
F1 Race Stars: Powered Up Edition - Regression (GX2RInvalidateSurface)

### ISSUE THREAD

**Issue by JohnGodgames** [decaf-emu/decaf-emu#358]
Regression caused by e6c53d4 ("gx2: Implement GX2RInvalidateSurface.", 2016-08-15)

**F1 Race Stars: Powered Up Edition**

7db1960
![f1 reg 1](https://cloud.githubusercontent.com/assets/11453507/17914895/550043b0-69a6-11e6-9ff0-298b9da7c579.JPG)

e6c53d4
![f1 reg 2](https://cloud.githubusercontent.com/assets/11453507/17914899/5b881712-69a6-11e6-9ed2-f2b69f323086.JPG)

**Comment by brett19** [comment]
This function appears implemented now.
