### ISSUE TITLE
Games  / Logs  / Issues 

### ISSUE THREAD

**Issue by SakataGintokiYT** [decaf-emu/decaf-emu#359]
**Build [  88dbe36  ]**

**Adventure Time Finn and Jake Investigations**
```
Expression: !(imageAddress & 0xff)
File: ..\src\libdecaf\src\modules\gx2\gx2_texture.cpp
Line: 158
```
Log : https://gist.github.com/SakataGintokiYT/0e4e7544929c1b555fcb761f27da194f

_____________________________________________________________________________________________________________

**Donkey Kong Country Tropical Freeze**
```
Expression: 0
File: ..\src\libdecaf\src\gpu\opengl\glsl2_translate.cpp
Line: 765
Message: GLSL translate exception: Unable to decode VTX instruction
```
Log : https://gist.github.com/SakataGintokiYT/999375d7057b5c802a10ced3defe2042
_____________________________________________________________________________________________________________

**Captain Toad: Treasure Tracker**
```
Expression: data.dstDim == data.srcDim
File: ..\src\libdecaf\src\gpu\opengl\opengl_driver.cpp
Line: 246
```
Log : https://gist.github.com/SakataGintokiYT/c2f3b259bec17ca5d44141e98b9abdb9

____________________________________________________________________________________________________________

**New SUPER MARIO BROS. U**
Log : https://gist.github.com/SakataGintokiYT/e2a68383555d524a2dddd2db33157613

_____________________________________________________________________________________________________________

**Terraria**
Log : https://gist.github.com/SakataGintokiYT/b2113fee2b3d2fc9c46969032a81eede

_____________________________________________________________________________________________________________

**Super.Mario.Maker**
Log :https://gist.github.com/SakataGintokiYT/5bd55937a79950cebc72e7e4ad3f8322

_____________________________________________________________________________________________________________

**Pokkemon Tournament**
```
Expression: lockValue & 1
File: ..\src\libdecaf\src\modules\coreinit\coreinit_fastmutex.cpp
Line: 308
```
Log : https://gist.github.com/SakataGintokiYT/ff376c081a6d6e5dbf913e71c475316e

_____________________________________________________________________________________________________________
**Minecraft** 

```
Expression: mutex->tag == OSFastMutex::Tag
File: ..\src\libdecaf\src\modules\coreinit\coreinit_fastmutex.cpp
Line: 103
```
Log : https://gist.github.com/SakataGintokiYT/601b3e8d0e57f2323a2104b9d04e9344

_____________________________________________________________________________________________________________

**Splatoon**
Log : https://gist.github.com/SakataGintokiYT/aa8d1bda9d537c55f7477182e84b0559

_____________________________________________________________________________________________________________
**Mario Kart 8** 
```
Expression: !(mipAddress & 0xff)
File: ..\src\libdecaf\src\modules\gx2\gx2_texture.cpp
Line: 157
```
Log : https://gist.github.com/SakataGintokiYT/2517daa9b9109919974a35d8a55be8dc
_____________________________________________________________________________________________________________

**Comment by exjam** [comment]
We really need to fix the stacktrace...!

**Comment by SakataGintokiYT** [comment]
[Build eb66db2 ] / nn_act: Generate a valid Mii instead of using dumped data
@brett19 
**Mario Kart 8** 
```
Assertion failed:
Expression: !(mipAddress & 0xff)
File: ..\src\libdecaf\src\modules\gx2\gx2_texture.cpp
Line: 157
```
Log :  https://gist.github.com/SakataGintokiYT/fca207aea7fae4583aa0a21ce2ceaf74

____________________________________________________________________________________________________________

**One Piece :** 
```
Assertion failed:
Expression: internal::isThreadActiveNoLock(thread)
File: ..\src\libdecaf\src\modules\coreinit\coreinit_thread.cpp
Line: 292
```
Log : https://gist.github.com/SakataGintokiYT/40b40b645bf245d923ff0588836a8302

**Comment by SakataGintokiYT** [comment]
updated logs

**Comment by brett19** [comment]
@SakataGintokiYT It would be ideal if you contributed with pcmaker and others on a single canonical repository of logs and known issues.  This would be far more helpful than me getting emails all day from you updating a ticket.

**Comment by brett19** [comment]
Just as a quick addition, I don't want you to feel like we don't want you're logs, or don't appreciate what you're doing.  It's simply that we need a central place to find and look at this information, otherwise its going to go to waste!

**Comment by Adubbz** [comment]
Might be worth asking pcmaker for edit permissions to https://docs.google.com/spreadsheets/d/1ydy1OVOayLgrEXu_1K9SQigYv7FJnbMJpQyOvBywNyY/edit#gid=0 since I think that's generally the go-to place nowadays.

**Comment by brett19** [comment]
To be fair, the structure of that document still makes it very difficult for us to grok.  The mainly useful part of that document is the "BROKEN" section, which is not actually kept up to date :(
