### ISSUE TITLE
My fear of red is stopping me from using Decaf

### ISSUE THREAD

**Issue by perezdev** [decaf-emu/decaf-emu#364]
Problem: Red murdered my uncle. I can't open Decaf.

Solution: Add background color option to Decaf config.

**Comment by PickledChris** [comment]
I have a fear of config options which allow the changing of background colours. This change would render me unable to use Decaf.

**Comment by perezdev** [comment]
He was MURDERED, man. MURDERED. Do you have no compassion?

**Comment by PickledChris** [comment]
I sympathise, I was murdered once, it was awful. But I would be #TRIGGERED if I had to use Decaf with that config option in place, it is unfortunate that our workflows clash so diametrically.

**Comment by ttay24** [comment]
How in depth would this config be? Could we use a custom background image? That could be fantastic..





On Thu, Aug 25, 2016 at 11:14 AM -0500, "Chris" <notifications@github.com> wrote:












I sympathise, I was murdered once, it was awful. But I would be #TRIGGERED if I had to use Decaf with that config option in place, it is unfortunate that our workflows clash so diametrically.

**Comment by exjam** [comment]
Probably want like

"display": {
"background_color": [255, 128, 0]
}

**Comment by perezdev** [comment]
@exjam It's beautiful

**Comment by PickledChris** [comment]
I feel ill

**Comment by achurch** [comment]
I propose a config option which enables a config option to change the background color.

See RFC 1925 (11a).

**Comment by perezdev** [comment]
@achurch I reject section 2 article 2.<sup>Don't let your dreams be dreams</sup>

**Comment by VelocityRa** [comment]
@perezdev I can't bring your uncle back, but at least now you can change the background color in Decaf.

**Comment by perezdev** [comment]
@VelocityRa 

You are a God among men. My uncle can rest easy now.

**Comment by VelocityRa** [comment]
@exjam Close this?
