### ISSUE TITLE
Failed to play game

### ISSUE THREAD

**Issue by ProfessorKaos64** [decaf-emu/decaf-emu#365]
Trying to test Super Smash Bros. Brawl for fun (yes I know things are experimental). I checked out the help text, and --log-file reports that the option "log-file" does not exist. What log output can I review to determine why this fails? Is there a "sure thing" game I can use to test?

From inside the source tree after building:
```
cmake_build/src/decaf-sdl/decaf-sdl play Wii/super-smash-bros-brawl.iso
[info] Game path ../Wii/super-smash-bros-brawl.iso
[info] Loaded config from /home/desktop/.config/decaf/config.json
[error] Failed to start game
```

ldd: http://sprunge.us/DfIU

File stat:
```
decaf-emu/cmake_build/src/decaf-sdl/decaf-sdl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```

**Comment by MoochMcGee** [comment]
Wii != Wii U, you fucking simpleton. If you want to play Brawl on your
computer, use Dolphin.

**Comment by ProfessorKaos64** [comment]
Shit I didn't see, no need to be a dick.

**Comment by exjam** [comment]
Also we do not support loading from .iso files

**Comment by ProfessorKaos64** [comment]
@exjam , I didn't see in the wiki. Is there a resource on dumping my game raw content, or the expected format?

**Comment by exjam** [comment]
You'd have to check the Wii wiki... Wii U games either come as .WUD or already extracted, if they are .WUD you use DiscU.

**Comment by ProfessorKaos64** [comment]
Same thing with a .WUD of Super Mario 3D Land. Maybe I need to extract it.

**Comment by exjam** [comment]
Yes, decaf does not support loading .WUD files either. Only extracted files.
