### ISSUE TITLE
CUBE instruction should handle SEL_0 and SEL_1 src

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#366]
This currently throws an assert due to incorrect logic checking in the CUBE instruction which checks if all the SRC are similar. From reading AMD docs I believe only the DST needs to be checked to be the same register, not the SRC.

```
    2 x: CUBE            R127.x, 0.0f, 1.0f
      y: CUBE            R127.y, 0.0f, 0.0f
      z: CUBE            R127.z, 0.0f, 0.0f
      w: CUBE            R127.w, 1.0f, 0.0f
```

@achurch  could you take a look? This is from Mario Kart 8 btw.

**Comment by achurch** [comment]
I already don't require all SRC to come from the same register, just that associated components in SRC0 and SRC1 are the same. What's the exact assert message?

**Comment by exjam** [comment]
It's the first one, "Invalid CUBE syntax: X/Y/Z elements are not distinct"

https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/gpu/opengl/glsl2_alu_reduction.cpp#L53-L58

**Comment by exjam** [comment]
More specifically, because "xSel == zSel && xRel == zRel && xChan == zChan", because both sources are SEL_0 (0.0f)

**Comment by achurch** [comment]
Ah, okay. I guess that check is safe to delete in the sense that we can still get the expected output.

We can't delete the inconsistent operand check because we don't implement CUBE exactly as the hardware does -- I don't know how the hardware would handle e.g. "CUBE R3.xyzw, R1.xyzw, R2.xyzw".
