### ISSUE TITLE
Include git sha in the log

### ISSUE THREAD

**Issue by Adubbz** [decaf-emu/decaf-emu#368]
A line with the name and product code from app.xml should suffice. This is so it can be extracted for use in the compatibility spreadsheet. Additionally the Git sha would be handy to track which versions certain issues occur in.

**Comment by exjam** [comment]
cf33c2d04b78c3c9dea8678eaa29600347eaf0e4 has game info, but not git sha

**Comment by exjam** [comment]
4c316d0b95e465651ecf7471dc7ef378294abc76
