### ISSUE TITLE
Crash upon loading Mario Kart 8

### ISSUE THREAD

**Issue by JaceCearK1** [decaf-emu/decaf-emu#371]
Not much I can say, I only got these two screenshots available for you:
![decaf](https://cloud.githubusercontent.com/assets/11230293/18064807/521b65fa-6e31-11e6-9f7a-9e3a2d93e5bb.JPG)
![decaf2](https://cloud.githubusercontent.com/assets/11230293/18064808/521c0a5a-6e31-11e6-8ed8-ebf3687650f9.JPG)
I hope you can make some use out of it! :)

**Comment by brett19** [comment]
God damnit @exjam.

**Comment by brett19** [comment]
@JaceCearK1: Oh right, forgot to answer the issue.

This issue is related to your system data being missing.  Please update your config's system_path to point to the correct system data folder.  Note that fixing your system data folder will just lead you to another, as of yet unsolved crash (which is why @exjam assigned this to me).

**Comment by exjam** [comment]
AKA you need title 0005001b-10056000 from NUS extracted such that the following exists:
<system_path>/mlc/sys/title/0005001b/10056000/content/FFLResMiddle.dat

**Comment by JaceCearK1** [comment]
Alright, thanks guys!
So, shall the path point to .../mlc or .../mlc/sys?
Maybe you guys should put an FAQ/Setup-Guide onto the main README.md, so things can be figured out without wasting your time with the same questions over and over! :)

**Comment by exjam** [comment]
Sorry github markdown ate my \< \>, i meant to do:

\<system_path\>/mlc/sys/title/0005001B/10056000/content/FFLResMiddle.dat

**Comment by JaceCearK1** [comment]
I'm sorry to disappoint you, but it throws out the exact same error both after defining it in the console window **and** in the config file.

**Comment by exjam** [comment]
oh well, it would only crash like 0.1s later anyway :) :+1:
