### ISSUE TITLE
MK8 significantly slower in some screens on Linux

### ISSUE THREAD

**Issue by shinyquagsire23** [decaf-emu/decaf-emu#380]
Tested on my desktop system with an FX-8350 + GTX 970 and on my laptop with an i5-6200U. The titlescreen and menu will have somewhat bearable framerates. I might boot into Windows to do tests there to validate it's purely a Linux issue and not just me lagging to death, but the effect is pretty considerable. During loading I might get a solid 60FPS aside from some momentary hangs, the transition from loading to the title screen is also fluid, but from there slows to about 0.5-10FPS, and in the Singleplayer screen slows to 0.1FPS.

During the transition and into the Singleplayer screen I get a pretty consistent spew of unimplemented snd_core functions for each frame every 10 seconds, although I also get no sound.

I'm guessing the issue either has something to do with timing on Linux (the singleplayer screen has a consistently rotating background as opposed to the static background in the menu) possibly causing some threads to sleep too long, or it's related to the hackfix in #379. Could also just be bad specs.

**Comment by brett19** [comment]
This is mostly fixed I believe.  We test MK8 on a regular basis.
