### ISSUE TITLE
CB_SHADER_MASK improperly handled

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#381]
CB_SHADER_MASK needs to be passed to the shader generator so that it can appropriately output the correct values for SHADER_MASK'd components.  This is required because CB_SHADER_MASK does not disable writing, but rather disables the output from the shader itself (a value is still written to the color buffer).

**Comment by SakataGintokiYT** [comment]
off topic:
any update ?

**Comment by exjam** [comment]
Fixed in Vulkan backend.
