### ISSUE TITLE
CB_SHADER_CONTROL does not appear to really exist

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#382]
As far as I can tell from any documentation, there is no such thing as CB_SHADER_CONTROL!?  We use it in OpenGL backend, not sure where it came from though.

**Comment by achurch** [comment]
GX2SetPixelShader seems to write it directly from the shader struct, see https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/modules/gx2/gx2_shaders.cpp#L183
I haven't actually disassembled the function myself so I can't speak to whether it's accurate to CafeOS.

**Comment by exjam** [comment]
You have to look at more than JUST the r600 pdf, remember the GPU is not a stock r600!

http://lmgtfy.com/?q=%22cb_shader_control%22
