### ISSUE TITLE
Mario party 10 crashes before i get to the main menu.

### ISSUE THREAD

**Issue by Bloop37** [decaf-emu/decaf-emu#383]
I was trying to play mario party 10 on the decaf emulator, but before the main menu loads, I get this error:

[41:46.166192 critical:w108] Assertion failed:
Expression: thread->context.fiber == nullptr
File: ..\src\libdecaf\src\modules\coreinit\coreinit_thread.cpp
Line: 194
Stacktrace:
12: SDL_SetClipboardText - 0x7FF7D0298C40x
11: SDL_SetClipboardText - 0x7FF7D0298C40x
10: SDL_SetClipboardText - 0x7FF7D0298C40x
9: SDL_SetClipboardText - 0x7FF7D0298C40x
8: SDL_SetClipboardText - 0x7FF7D0298C40x
7: SDL_SetClipboardText - 0x7FF7D0298C40x
6: SDL_SetClipboardText - 0x7FF7D0298C40x
5: SDL_SetClipboardText - 0x7FF7D0298C40x
4: SDL_SetClipboardText - 0x7FF7D0298C40x
3: SDL_SetClipboardText - 0x7FF7D0298C40x
2: SDL_SetClipboardText - 0x7FF7D0298C40x
1: SDL_SetClipboardText - 0x7FF7D0298C40x
0: SDL_SetClipboardText - 0x7FF7D0298C40x

I tried to ignore it, but after I clicked the ignore button, the emulator immediately crashes. Is there any way to fix this? Here's the full error log:

[Mario Party 10 [ABAE01]_2016-10-03_11-40.txt](https://github.com/decaf-emu/decaf-emu/files/506963/Mario.Party.10.ABAE01._2016-10-03_11-40.txt)

**Comment by Parovozik** [comment]
Mario Party 10 works on build from March28 (unstable, but works)
[YouTube Video MP10_Decaf](https://www.youtube.com/watch?v=shk9h2roVu0)
For last builds (after March 28) only main menu

**Comment by exjam** [comment]
Fixed.
