### ISSUE TITLE
i miss decaf

### ISSUE THREAD

**Issue by Gamedev1909** [decaf-emu/decaf-emu#385]
i miss you decaf devs come back to use please 
we need a proper wii u emulator

**Comment by brett19** [comment]
<3

**Comment by sergiotapia** [comment]
It's a shame how development slowed down. Decaf progressed so quickly and so far! Hope you guys come back! An open source Wii U emu means users in 2035 will be able to run Wii U games in Windows 20. :)

**Comment by lbalan791** [comment]
There are new commits this month. :)

**Comment by ikki84** [comment]
What´s happening?

**Comment by brett19** [comment]
What isn't happening?

**Comment by neobrain** [comment]
What is both happening and not happening at the same time?

**Comment by brett19** [comment]
Decaf.

**Comment by exjam** [comment]
memepicture.jpg

**Comment by Gamedev1909** [comment]
We wait thats all thats going on 2017 i hope is a good year for decaf make it so number 1

**Comment by ikki84** [comment]
@brett19 Just to know that we still miss your job in decaf. also exjam and achurch.

**Comment by Gamedev1909** [comment]
As cemu is completely broken we need you all back badly

**Comment by tykel** [comment]
Guys! Your incantations worked! https://github.com/decaf-emu/decaf-emu/compare/aaa78a82bb...365d506712 ^__^

**Comment by Gamedev1909** [comment]
as of now i am willing to donate 5$ a month to keep you guys working and when i get that 5$ i will find away

**Comment by CoalaJoe** [comment]
Please make a Petreon

**Comment by exjam** [comment]
We all have full time jobs and things to do in real life, this is just a hobby we do in our spare time, receiving 5$ a month doesn't magically give us more free time!
