### ISSUE TITLE
git submodule update --init fails

### ISSUE THREAD

**Issue by Elinvention** [decaf-emu/decaf-emu#398]
```
$ git submodule update --init ../libraries/asmjit
Fetched in submodule path '../libraries/asmjit', but it did not contain 6467c73ddfd6be1bd90104fab35676f26c319d54. Direct fetching of that commit failed.
```

**Comment by exjam** [comment]
I'm not sure what to suggest, both the [appveyor](https://ci.appveyor.com/project/exjam/decaf-emu) & [travis](https://travis-ci.org/decaf-emu/decaf-emu) builds run just fine, and it works locally on my machines... and that commit exists on [github/asmjit/asmjit](https://github.com/asmjit/asmjit/tree/6467c73ddfd6be1bd90104fab35676f26c319d54) still.

```
git clone https://github.com/decaf-emu/decaf-emu.git
cd decaf-emu
git submodule update --init --recursive
```

**Comment by Elinvention** [comment]
Sorry, I don't know what went wrong... but now it works. Thanks.
