### ISSUE TITLE
Implement basic rendering

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#40]
Implement the basic requirements for rendering from a game.

**Comment by brett19** [comment]
Check it out, we rendering some stuff now!  http://puu.sh/kG09t.png

**Comment by JohnGodgames** [comment]
great

**Comment by sasukedotca** [comment]
thats nice ! it's actually a good start !

**Comment by brett19** [comment]
Got some textures, but the still needs a lot of work...
http://puu.sh/kItba.png

**Comment by tykel** [comment]
Awesome progress guys!

**Comment by JohnGodgames** [comment]
Impressive!

**Comment by exjam** [comment]
Current state

![2015-10-14_02-00-10](https://cloud.githubusercontent.com/assets/1302758/10472402/f606925a-7217-11e5-8214-e5c84031e576.png)

**Comment by exjam** [comment]
Progress.

https://puu.sh/l1cFs/3cf90ef641.png

**Comment by VelocityRa** [comment]
Great work guys!

**Comment by sasukedotca** [comment]
Really good ! Rendring 2D already !
We need an fps counter on the window title :D

**Comment by tykel** [comment]
For reference, what it should look like:
![](http://media.nintendo.com/nintendo/bin/I8WpPmZ9Yiz5cGVwtQG-HyR7tKtBQTs2/dmmnAhGU29mpnhk3eDC3kCIJWV1IZhIt.jpg)

We're not that far off here.

**Comment by brett19** [comment]
Tada!
![ss 2015-10-29 at 11 49 45](https://cloud.githubusercontent.com/assets/1621627/10837392/d1f4776a-7e97-11e5-99c8-7c39bb7f5174.jpg)

**Comment by waddlesplash** [comment]
What's the bottom image? GamePad output?

**Comment by brett19** [comment]
Indeed.

**Comment by VelocityRa** [comment]
How is it doing framerate-wise atm?
