### ISSUE TITLE
decaf-emu default unix install missing bindir, sharedir, confdir

### ISSUE THREAD

**Issue by rcampbel3** [decaf-emu/decaf-emu#407]
When I build decaf-emu from latest source using defaults provided by cmake, everything works as expected. When I do a 'sudo make install', it installs as follows:

<pre>
-- Install configuration: ""
-- Up-to-date: /usr/local/libglbinding.so
-- Installing: /usr/local/decaf-cli
-- Installing: /usr/local/decaf-sdl
-- Installing: /usr/local/gfd-tool
-- Installing: /usr/local/tests/hardware-test
-- Installing: /usr/local/tests/hardware-test-generator
-- Installing: /usr/local/tests/hardware-test-achurch
-- Installing: /usr/local/pm4-replay
-- Up-to-date: /usr/local/resources/fonts/DejaVuSansMono.ttf
-- Up-to-date: /usr/local/resources/fonts/SourceSansPro-Regular.ttf
-- Up-to-date: /usr/local/resources/fonts/LICENSE.txt
</pre>

it should be installing binaries to $PREFIX/bin
It should be installing most other things under $PREFIX/share

**Comment by Tatsh** [comment]
This is in #527
