### ISSUE TITLE
Virtual Reality

### ISSUE THREAD

**Issue by CarlKenner** [decaf-emu/decaf-emu#408]
I've currently added crude Oculus Rift support here:
https://github.com/CarlKenner/decaf-emu/tree/VR

It renders the TV and DRC screens to virtual screens in VR, and makes the DRC screen be the right size and attached to your hand, and you can use it like a touch screen in VR. I could also draw a room or other virtual environment for the screens to be in, or add a skybox.

But what I want to do is put the user inside the virtual world like I do in Dolphin VR. To do that, I need to:

- ~~Check each uniform to see if it's a view/projection matrix and if so, adjust it to match the FOV of the HMD and to add head tracking before passing it to the graphics card.~~
- Change 2D textures into 2D texture arrays.
- Add a geometry shader to double the geometry and send it to each eye layer with appropriate eye separation and convergence.
- If there's already a geometry shader, modify the geometry shader to do that too.
- (Ideally) read the view/projection matrices to try to estimate when and how the game has moved the camera.
- (Ideally) hook certain game functions (that aren't imports or exports), so I can change their inputs and outputs. For example, the camera functions, or the view frustum culling functions.
- Add per-game settings for scale etc., like how many game units there are per metre, which will be different for every game.
- Add a way to render the same frame's pm4 commands twice or three times (but with updated head tracking), to bring the frame rate up to 90 FPS.
- Add other ways to run the game at either 90 FPS or 45 FPS.

I've started working on some of these things, but let me know if you have any guidance on how you want them done or not done, or what the best way to do them would be.

**Comment by CarlKenner** [comment]
I've managed to get it so I can read and modify the view and projection matrices now, and recalculate all the other constants that are based on them. At least, I can in Xenoblade X. Now I just need to plug in the rotations, translations, and FOV from the HMD.

BTW, are there any other 3D games that are working? Most of the games I've got that work in Decaf are 2D only.

**Comment by exjam** [comment]
From what I've seen, One Piece: Unlimited World Red is the best working 3D game right now imo.

**Comment by VelocityRa** [comment]
Yeah, it's pretty cool and I can appreciate the effort for all this, but I think that at this point Decaf needs a lot more work in other areas (IOSU HLE, graphics backend, shaders, etc) for VR support to make sense.

Nothing wrong with tinkering around of course, I may have attempted this as well if I owned a VR headset :)

**Comment by CarlKenner** [comment]
I did some work in other areas too. I even made an IDA script that names functions based on what imports they call, so we can work on supporting games that don't have debug symbols.

VR support would make sense for Cemu, but it's not open source, so that's not an option. Decaf will catch up eventually though. Or Cemu will go open source and we can port features across. Interestingly, Shovel Knight works much better in Decaf than in Cemu, so we're doing some things right.

I had to pass the information from the GX2VertexShader to the opengl Shader backend, because we normally throw most of the information away.

**Comment by CarlKenner** [comment]
I got the head-tracking and FOV working. So I can walk around the title screen and character screen in Xenoblade (I haven't tested anywhere else yet). Some effects are still screenspace, but I know how to deal with that later.

But I can only see out of one eye. Stereoscopic rendering to layers using geometry shaders is going to be more difficult.

**Comment by brett19** [comment]
I'm going to close this for now, not because I don't think its really awesome, but rather that I think that it belongs in a separate project as opposed to being part of decaf itself.  I would say that it's probably worthwhile to open an issue related to implementing a plugin system with hooks that allow you to do this.  I'd also suggest you take ownership for it, since I have no bloody clue what you would hook to make this happen :D
