### ISSUE TITLE
Darksiders II: fail to boot, segment loader runs out of memory

### ISSUE THREAD

**Issue by FernandoS27** [decaf-emu/decaf-emu#421]
The game tries to create a 162mb loadSegment on kernel loading but fails to boot due to the heap loader not being able to allocate that much memory.

Debug info:
loadSize	172158432 (0x0a42ede0)	be_val<unsigned int>, loadAlign	4 (0x00000004)	be_val<unsigned int>
LoadSegment: 0x00000000000000000000ul

line:
decaf\src\libdecaf\src\kernel\kernel_loader.cpp
Line: 970

**Comment by achurch** [comment]
Might be fixed by the fix for #401.

**Comment by exjam** [comment]
Nope not fixed, this is a separate issue where the game has RPL_FILEINFO.loadSize = 0x0a42ede0 (164mb) and our loader heap is smaller than that.

**Comment by exjam** [comment]
This would have been fixed a while ago with the loader rewrite.
