### ISSUE TITLE
Linux Compile Errors

### ISSUE THREAD

**Issue by Gamedev1909** [decaf-emu/decaf-emu#433]
Issue was LIBSDL2dev wasnt installed thanks to @jroweboy for the help

**Comment by jroweboy** [comment]
Did you accidentally turn on the cmake DECAF_VALGRIND option? Its looking for valgrind and can't find it, but decaf doesn't build with it by default, so just turn that option off.

**Comment by MoochMcGee** [comment]
@Gamedev1909 Bro, I can tell you're not even trying.

**Comment by Gamedev1909** [comment]
wrong issue fixed OP comment

**Comment by MoochMcGee** [comment]
Install SDL2 lol

**Comment by Gamedev1909** [comment]
it's installed by default 
now what

**Comment by MoochMcGee** [comment]
Make sure it's installed, then compile again. Are you dense or something?

**Comment by jroweboy** [comment]
@Gamedev1909 i'm guessing you are missing libsdl2-dev if you are using ubuntu. The error says that its missing the sdl2 static library, which usually comes separate from sdl2.

**Comment by Gamedev1909** [comment]
the instructions are lacking sadly if you can't tell

**Comment by Gamedev1909** [comment]
thanks @jroweboy at least someone knows how to help you rock i might have to write a linux compile guide
