### ISSUE TITLE
Zelda must perform a system update

### ISSUE THREAD

**Issue by paulguy** [decaf-emu/decaf-emu#437]
I don't know if I'm just missing something or what but I've been trying to test this game and other people seem to get to a point where the game actually tries to run, I just get a message about it needing to perform a system update.

http://imgur.com/a/M9R0n

I'm using decaf-emu commit 0986d10cdbe892716d1f9f42dfcf13eb9f9f9e59

**Comment by VelocityRa** [comment]
I'm not sure if others experience the same issue, but can you provide a log?

**Comment by Gamedev1909** [comment]
Merge the update 1.0 or newer with main game

**Comment by paulguy** [comment]
Ah yeah, sorry for the dumb question.  I got it going.  It crashes after nintendo presents now but I imagine youse already know that.  Thanks.
