### ISSUE TITLE
Zelda - Breath of the Wild [No input]

### ISSUE THREAD

**Issue by Axlkris** [decaf-emu/decaf-emu#438]
Loading the game with a save file to get in menus, but it doesn't seem to recognize any input or display the blinking cursor(arrow) as seen in the screenshot. Also it looks a little darker than it should.

![decaf](https://cloud.githubusercontent.com/assets/5333526/25842267/c75f3448-34a3-11e7-9fa8-7497150ebc09.PNG)

Edit: Figured how to create a log file and found that it's failing to load missing Vpadbase.rpl module.
Also more interesting info in it.
[U-King.rpx_2017-05-09_22-40.txt](https://github.com/decaf-emu/decaf-emu/files/987982/U-King.rpx_2017-05-09_22-40.txt)

**Comment by VelocityRa** [comment]
Can you be a bit more specific about how you got to that point? Does it still get there with current master?

Did you have to comment out asserts to get there? Or did you just use AppVeyor builds? What about the save file?

**Comment by Axlkris** [comment]
Tested with latest build from appveyor and all is the same. Should have latest commits.
Put the save file inside mlc folder.
For me it's both these folders:
..\decaf\mlc\usr\save\0005000e\101c9400\user\80000001\(save here)
..\decaf\mlc\usr\save\00050000\101c9400\user\80000001\(save here)
Should be something similar for you too depending on game region.

**Comment by EmulationChannel** [comment]
@Axlkris @VelocityRa Oky Decaf Master Build Laster not boot in Zelda Botw on Menu The Soon
![anotacao 16](https://user-images.githubusercontent.com/37957125/47577322-fa82fc00-d91c-11e8-95f8-9f89a66016f0.png)

**Comment by brett19** [comment]
@exjam fixed this a while back and there is a new issue related to the vulkan backend which is being worked on.
