### ISSUE TITLE
AmiboSettings blows up

### ISSUE THREAD

**Issue by brett19** [decaf-emu/decaf-emu#44]
We've been doing graphical testing using AmiiboSettings and we've noticed that after a while the graphics start to blow up and eventually the game crashes.  I've narrowed it down to a function (sub_20EA924) running on another thread which is looping, starting at around 0x15F698C0, and decrementing by 0x800 on each iteration.  It's doing a `memset(addr, 0, 0xc)` (loc_20EAD08) which slowly corrupts game memory until it reaches the game code memory which is when the app blows up.

cc: @exjam @zhuowei @Kinnay

**Comment by Kinnay** [comment]
This might help: sub_20EA924 is nw::scfont::TextureCache::UpdateTextureCache((void)).

**Comment by exjam** [comment]
I'd bet on it being a bug in the interpreter somewhere!

**Comment by exjam** [comment]
Behaves differently now.
