### ISSUE TITLE
Duplicate latte register enum values

### ISSUE THREAD

**Issue by petmac** [decaf-emu/decaf-emu#448]
I tried using the enum latte::Register::Value in a switch statement, and the compiler complained that a number of cases had duplicate values:

   PA_SC_VPORT_ZMIN_0               = 0x282D0,
   PA_SC_VPORT_ZMAX_0               = 0x282D4,
   PA_SC_VPORT_ZMIN_1               = 0x282D8,
   PA_SC_VPORT_ZMAX_1               = 0x282DC,
   PA_SC_VPORT_ZMIN_2               = 0x282D0,
   PA_SC_VPORT_ZMAX_2               = 0x282D4,
   PA_SC_VPORT_ZMIN_3               = 0x282D8,
   PA_SC_VPORT_ZMAX_3               = 0x282DC,
   PA_SC_VPORT_ZMIN_4               = 0x282D0,
   PA_SC_VPORT_ZMAX_4               = 0x282D4,
   PA_SC_VPORT_ZMIN_5               = 0x282D8,
   PA_SC_VPORT_ZMAX_5               = 0x282DC,
   PA_SC_VPORT_ZMIN_6               = 0x282D0,
   PA_SC_VPORT_ZMAX_6               = 0x282D4,
   PA_SC_VPORT_ZMIN_7               = 0x282D8,
   PA_SC_VPORT_ZMAX_7               = 0x282DC,
   PA_SC_VPORT_ZMIN_8               = 0x282D0,
   PA_SC_VPORT_ZMAX_8               = 0x282D4,
   PA_SC_VPORT_ZMIN_9               = 0x282D8,
   PA_SC_VPORT_ZMAX_9               = 0x282DC,
   PA_SC_VPORT_ZMIN_10              = 0x282D0,
   PA_SC_VPORT_ZMAX_10              = 0x282D4,
   PA_SC_VPORT_ZMIN_11              = 0x282D8,
   PA_SC_VPORT_ZMAX_11              = 0x282DC,
   PA_SC_VPORT_ZMIN_12              = 0x282D0,
   PA_SC_VPORT_ZMAX_12              = 0x282D4,
   PA_SC_VPORT_ZMIN_13              = 0x282D8,
   PA_SC_VPORT_ZMAX_13              = 0x282DC,
   PA_SC_VPORT_ZMIN_14              = 0x282D0,
   PA_SC_VPORT_ZMAX_14              = 0x282D4,

   SQ_TEX_RESOURCE_WORD0_0          = 0x38000,
   SQ_TEX_RESOURCE_WORD1_0          = 0x38004,
   SQ_TEX_RESOURCE_WORD2_0          = 0x38008,
   SQ_TEX_RESOURCE_WORD3_0          = 0x3800C,
   SQ_TEX_RESOURCE_WORD4_0          = 0x38010,
   SQ_TEX_RESOURCE_WORD5_0          = 0x38014,
   SQ_TEX_RESOURCE_WORD6_0          = 0x38018,
   SQ_VTX_CONSTANT_WORD0_0          = 0x38000,
   SQ_VTX_CONSTANT_WORD1_0          = 0x38004,
   SQ_VTX_CONSTANT_WORD2_0          = 0x38008,
   SQ_VTX_CONSTANT_WORD3_0          = 0x3800C,
   SQ_VTX_CONSTANT_WORD4_0          = 0x38010,
   SQ_VTX_CONSTANT_WORD5_0          = 0x38014,
   SQ_VTX_CONSTANT_WORD6_0          = 0x38018,

I'm not sure what the correct values should be, so I'll just comment them out in my code for now.

**Comment by exjam** [comment]
Fixed, PA_SC_VPORT had wrong values, and I unified the SQ_TEX_RESOURCE and SQ_VTX_CONSTANT to an SQ_RESOURCE enum.

[gpu: Unify resource register enum values into SQ_RESOURCE_WORDX_Y. ](https://github.com/decaf-emu/decaf-emu/commit/939fe9bfe0fc761e925b3aa95c21f747ad1b490a)

[gpu: Fix values for register enums PA_SC_VPORT_{ZMIN,ZMAX}.](https://github.com/decaf-emu/decaf-emu/commit/1efa3aafa49dc8c418568d04a7e1990ed07116f9)
