### ISSUE TITLE
Linux Issues

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [decaf-emu/decaf-emu#450]
```
/tmp/yaourt-tmp-gamedev1909/aur-decaf-emu-git/src/decaf-emu/libraries/imgui/imgui_draw.cpp:1201: ImFont* ImFontAtlas::AddFontFromFileTTF(const char*, float, const ImFontConfig*, const ImWchar*): Assertion `0' failed.
Aborted (core dumped)
```
any idea 4.9 kernel 290x 4790k manjaro linux and https://github.com/mikakev1/mesa_mild_compatibility

**Comment by Flat** [comment]
You're missing the Dejavu Sans Mono font

**Comment by Gamedev1909** [comment]
Oh where do I get that at any links if  you can’t link it can you email it to gamedev1909@gmail.com

**Comment by VelocityRa** [comment]
@Gamedev1909 You need to copy the `resources` folder to where the compiled `decaf-sdl` executable is.

**Comment by cowkid** [comment]
When one executes the file what happens? Any way you can make this work on
chromebook ubuntu Linux?

**Comment by hcorion** [comment]
@Gamedev1909 Assuming you used the the package from the ArchLinux AUR, you'll want edit `~/.config/decaf/config.toml`, there should a line that says
```
resources_path = "resources"
```
change that, to say
```
resources_path = "/usr/bin/resources"
```
Which is where the AUR package installs them (pretty bad position IMO, but that's where it is)

---

IMO this is still an issue, common fonts like these should try to load from the system-installed fonts first, so perhaps change the issue title to 
`Make decaf attempt to load fonts from system`

**Comment by Gamedev1909** [comment]
Little late on that the Mesa I used that bypasses the piss poor OpenGL in decaf for amd doesn’t work right now so even if I got things to run nothing would render like always
