### ISSUE TITLE
Crash in glbinding::initialize on Linux

### ISSUE THREAD

**Issue by schulmar** [decaf-emu/decaf-emu#454]
I am running Arch Linux with GCC 7.1.1 and 3.9.1 After having worked around the fonts issue (#450) I get a segmentation fault with the current master (9ea4708e1d7e3c14d6f447f660c3228fd6cc9bcb). 
Some manual tweaks were necessary to get not only decaf but also its 3rd party libraries to build in Debug mode. (This should be improved.)

I found that the crash occurs in `glbinding::Binding::initialize`.
This function is called multiple times. Have a look here:
https://github.com/decaf-emu/decaf-emu/blob/9ea4708e1d7e3c14d6f447f660c3228fd6cc9bcb/src/decaf-sdl/decafsdl_opengl.cpp#L381-L395
We have a call chain like this: `main->start->DecafSDL::initGlGraphics->DecafSDLOpenGL::initialise`  that calls `DecafSDLOpenGL::initialiseContext` (on line 381) which calls `glbinding::Binding::initialize` and successfully inserts one context into glbinding's global variable `g_bindings`.
On the second call to `DecafSDLOpenGL::initialiseContext` (on line 392) from thread 2, the contents of the static variable `g_bindings` seem to be invalid and it crashes in a private function some levels deeper than a call to `std::unordered_map<...>::find` in `glbinding::Binding::initialize`. A memory watchpoint on `g_bindings` indicated no changes between the write in the first call and the read in the second one.
I am not sure how to proceed further, any help would be appreciated.

**Comment by schulmar** [comment]
Having turned on logging I get this output:
```
[14:06.979209 debug:17023] reserveMemory(address: 0x100000000, size: 0x100000000) returned unexpected address: 0x7f771c000000
[14:06.981617 debug:17023] reserveMemory(address: 0x200000000, size: 0x60000000) returned unexpected address: 0x7f77bc000000
[14:06.981682 error:17023] Invalid physicalMemoryType 3 for mapMemory
[14:06.981690 error:17023] Unexpected failure allocating mapping virtual address 0xFFC00000 to physical address 0x02000000
[14:06.997712 error:17023] Could not find valid application at <redacted>
```
There might be a chance that this error only occurs when loading an invalid application. Obviously, there should be a better error message (especially when there is no debugging output.
Anyways, how do I find out what is wrong with my game data? (Sorry, I am quite new to Wii U emulation.)

**Comment by VelocityRa** [comment]
A full log would be helpful.

**Comment by schulmar** [comment]
I am not sure what you mean by full log but I added the other lines that were printed.

**Comment by VelocityRa** [comment]
Seems like it's an issue with allocating memory, but it may be something else. You could try running an application that's known to work like NES Remix Pack, to verify.

**Comment by schulmar** [comment]
After correcting the game folder it loads without this error. (Now I get an assertion on `sSaveInitialised`.)

Using the empty folder as "reproducer", I noticed that there seems to be a race condition between the main thread and the second one, where the main thread has already exited with "Failed to start game" while the ui thread is initializing the context.

**Comment by exjam** [comment]
No longer using glbinding.
