### ISSUE TITLE
Might need to set a maximum on MEMGetAllocatableSizeForExpHeapEx?

### ISSUE THREAD

**Issue by Kinnay** [decaf-emu/decaf-emu#455]
Donkey Kong Country: Tropical Freeze crashes almost immediately.

CGameAllocator::Initialize contains a piece of code that looks similar to this when decompiled:
```C++
int handle = MEMGetBaseHeapHandle(MEM2);
uint32_t size = MEMGetAllocatableSizeForExpHeapEx(handle, 0x10);
size -= 0x480000; //4.5MiB
if (size > 0x3E200000) size -= 0x3E200000; //994MiB
OSReport("Heap memory available: %dMB\n", size >> 20);
void *memory = MEMAllocFromExpHeapEx(handle, size, 0x10);
```
The weird part is that it checks if the size is greater than 0x3E200000. When I ran decaf-emu, the call to MEMGetAllocatableSizeForExpHeapEx returned 0x3E74EDA0, which made the game allocate a very small memory block for its heap.

**Comment by brett19** [comment]
Hey @Kinnay,
This is actually a known issue.  Oddly, some games have similar logic using completely different memory availability requirements, which is why DKCTF is currently broken (in order to fix lots of other games, we had to stop restricting the available memory).  We assume there is some sort of default allocator behaviour differences between DKCTF and the other games which will allow them to all work, but have yet to identify what that difference might be.
Cheers, Brett

**Comment by Kinnay** [comment]
I spent the past few days reversing kernel and loader, and I now know exactly how different memory regions are allocated from MEM2. I wrote a Python script to test my findings and verified it's right by comparing it with the results of OSGetMemBound, __KernelGetInfo and MEMGetBaseHeapHandle on my Wii U.

MEMGetAllocatableSizeForExpHeapEx actually returns an even smaller size on my Wii U (I'm guessing coreinit and other libraries allocate from it between creating the heap and calling the game entry point), but this should at least fix the crash in DKC:TF. It would be weird for games to rely on this anyway.

Here's the script: https://pastebin.com/QjGLRAk3

The list of shared libraries is hardcoded in loader.elf. The shared libraries are always loaded, even if they're not used by the game. Maybe you can hardcode their data size and alignment values? It'd suck if people needed to provide their own rpls to run decaf.

Anway, I hope this helps.

**Comment by exjam** [comment]
Seems to be fixed with new loader.
