### ISSUE TITLE
Assertion failed: vertex.outputMap[semanticId] == 0xff

### ISSUE THREAD

**Issue by Kinnay** [decaf-emu/decaf-emu#463]
This happens in GLDriver::compileVertexShader in the game Art of Balance.

I may have found the cause of this error by comparing the following shaders. Decaf only seems to copy num_spi_vs_out_id registers, clearing the others to 0, even though they're 0xFF in the original shader. If the spi_vs_out_ids exactly fit into num_spi_vs_out_id registers, no end marker is copied into GLDriver's internal registers, and the assertion error is triggered when the loop in compileVertexShader reaches one of the padding zeroes.

---
This is the shader that's triggering the error.

In GX2SetVertexShader:
```
spi_vs_out_config=00000020
num_spi_vs_out_id=00000003
spi_vs_out_id[0]=00 01 02 03
spi_vs_out_id[1]=04 06 07 08
spi_vs_out_id[2]=09 0B 05 0A
spi_vs_out_id[3]=FF FF FF FF
spi_vs_out_id[4]=FF FF FF FF
spi_vs_out_id[5]=FF FF FF FF
spi_vs_out_id[6]=FF FF FF FF
spi_vs_out_id[7]=FF FF FF FF
spi_vs_out_id[8]=FF FF FF FF
spi_vs_out_id[9]=FF FF FF FF
```

In GLDriver::compileVertexShader:
```
spi_vs_out_config=00000020
spi_vs_out_id[0]=00 01 02 03
spi_vs_out_id[1]=04 06 07 08
spi_vs_out_id[2]=09 0B 05 0A
spi_vs_out_id[3]=00 00 00 00
spi_vs_out_id[4]=00 00 00 00
spi_vs_out_id[5]=00 00 00 00
spi_vs_out_id[6]=00 00 00 00
spi_vs_out_id[7]=00 00 00 00
spi_vs_out_id[8]=00 00 00 00
spi_vs_out_id[9]=00 00 00 00
```

---
This is a random other shader.

In GX2SetVertexShader:
```
spi_vs_out_config=00000002
num_spi_vs_out_id=00000001
spi_vs_out_id[0]=00 01 FF FF
spi_vs_out_id[1]=FF FF FF FF
spi_vs_out_id[2]=FF FF FF FF
spi_vs_out_id[3]=FF FF FF FF
spi_vs_out_id[4]=FF FF FF FF
spi_vs_out_id[5]=FF FF FF FF
spi_vs_out_id[6]=FF FF FF FF
spi_vs_out_id[7]=FF FF FF FF
spi_vs_out_id[8]=FF FF FF FF
spi_vs_out_id[9]=FF FF FF FF
```

In GLDriver::compileVertexShader:
```
spi_vs_out_config=00000002
spi_vs_out_id[0]=00 01 FF FF
spi_vs_out_id[1]=00 00 00 00
spi_vs_out_id[2]=00 00 00 00
spi_vs_out_id[3]=00 00 00 00
spi_vs_out_id[4]=00 00 00 00
spi_vs_out_id[5]=00 00 00 00
spi_vs_out_id[6]=00 00 00 00
spi_vs_out_id[7]=00 00 00 00
spi_vs_out_id[8]=00 00 00 00
spi_vs_out_id[9]=00 00 00 00
```

**Comment by joaozin23** [comment]
@Kinnay 
![esboco 4](https://user-images.githubusercontent.com/17303493/31298882-8eafa4f8-aac2-11e7-86a5-4aaf5b173360.png)
![Uploading Esboço (5).png…]()
![Uploading Esboço (6).png…]()
![Uploading Esboço (7).png…]()
![Uploading Esboço (8).png…]()
![Uploading Esboço (9).png…]()
![Uploading Esboço (10).png…]()
![Uploading Esboço (11).png…]()
![Uploading Esboço (12).png…]()
![Uploading Esboço (2).png…]()
![Uploading Esboço (3).png…]()

**Comment by joaozin23** [comment]
![esboco 8](https://user-images.githubusercontent.com/17303493/31298887-8eb93266-aac2-11e7-8d46-d8585f94194b.png)
![esboco 9](https://user-images.githubusercontent.com/17303493/31298885-8eb8ef9a-aac2-11e7-88f2-656c5e9fea8e.png)
![esboco 10](https://user-images.githubusercontent.com/17303493/31298891-8ffec5aa-aac2-11e7-8941-7f19cfe93972.png)
![esboco 11](https://user-images.githubusercontent.com/17303493/31298890-8ffd0062-aac2-11e7-9df3-a48fd4a856e4.png)
![esboco 12](https://user-images.githubusercontent.com/17303493/31298892-9001269c-aac2-11e7-82ad-f3ca2f4b10d2.png)
![esboco 2](https://user-images.githubusercontent.com/17303493/31298888-8f12259c-aac2-11e7-8d50-485164965e8f.png)
![esboco 3](https://user-images.githubusercontent.com/17303493/31298889-8f1858fe-aac2-11e7-8746-49675ed86ff8.png)
![esboco 4](https://user-images.githubusercontent.com/17303493/31298935-b1c1160c-aac2-11e7-832a-5755564dda7d.png)
![esboco 5](https://user-images.githubusercontent.com/17303493/31298936-b255c108-aac2-11e7-8eab-b3bacbda2817.png)
![esboco 6](https://user-images.githubusercontent.com/17303493/31298937-b3179ab2-aac2-11e7-9f7b-231247ee7743.png)
![esboco 7](https://user-images.githubusercontent.com/17303493/31298938-b3c7894a-aac2-11e7-8cf9-416943593f1d.png)

**Comment by VelocityRa** [comment]
@joaozin23 Whatever it is you're doing, please stop; it's not helping anyone.

**Comment by brett19** [comment]
Looks like this is not nearly as simple as it looks.  I don't believe that using 0xFF as a delimiter is really safe anymore, the real answer here is to keep track of these semantics internally so that the writes can occur to the right locations.

**Comment by brett19** [comment]
Going to close this now that Vulkan is the primary driver.
