### ISSUE TITLE
New Super Mario Bros U Crashes after Leaving "Press (2)" Intro Screen

### ISSUE THREAD

**Issue by gralco** [decaf-emu/decaf-emu#470]
Unlike a few other games I have tested, "New Super Mario Bros U" actually starts, which is great! The only problem is that it crashes right after leaving the intro screen.

There seem to be people using Windows who are having success, albeit on older commits, so this may be an OS-specific issue.

Here is the log I got: https://pastebin.com/raw/4yjcK5if
Here is my config.toml file (untouched): https://pastebin.com/raw/feHDsnFR

Here are some details about my setup:
- Running Fedora 27 with kernel 4.14.8-300.fc27.x86_64
- Using GTX 970 with NVidia's proprietary driver on version 387.34, OpenGL 4.6.0
- Built glbinding v2.1.3 from source
- On commit db78b3a141473f36a00b2b14cbbf6bfefd24960c
- Built decaf-emu with the `-DDECAF_VALGRIND=ON` flag
- Used gcc-7.2.1-2.fc27.x86_64
- Ran the game with `--sound` and `--jit` flags

Please let me know if there's more info I can provide or if I should change something in my test. Maybe loading existing save states can allow me to test different parts of the game.

**Comment by VelocityRa** [comment]
There seem to be some libbinrec errors in there, did you try the interpreter? (`--no-jit`)

**Comment by gralco** [comment]
I just ran it with `--no-jit`. Besides being about an order of magnitude slower it didn't seem to do much, it crashed at the same spot.

No libinrec errors this time, here's the log: https://pastebin.com/raw/Fd9JuNnw
