### ISSUE TITLE
Should inform user about which graphics processor is being used

### ISSUE THREAD

**Issue by FailedShack** [decaf-emu/decaf-emu#480]
To avoid issues like the one below, where the error message is not particularly helpful. The graphics processor in use by Decaf should be printed to the console and the high performance graphics processor should take priority.

---

Decaf crashes every time I launch it with the following message:

> [error] Failed to create Main OpenGL context: Could not create GL context: La operaci├│n se complet├│ correctamente.
> 
> [error] Failed to create GL graphics window
> [error] Failed to initialise OpenGL backend.

The message after "Could not create GL context" translates to "The operation was completed successfully."

**Comment by VelocityRa** [comment]
Your GPU probably doesn't support OpenGL 4.5.
Which one (or CPU if there's no GPU) do you have?

**Comment by FailedShack** [comment]
I have a Nvidia Geforce 860M, according to the [specs sheet](https://www.geforce.com/hardware/notebook-gpus/geforce-gtx-860m/specifications) it does support OpenGL 4.5.

**Comment by VelocityRa** [comment]
Try updating your graphics drivers maybe?

If they're updated, you can disable integrated graphics through Device Manager (on Windows), then decaf and any other program will only be able to use your GPU.

**Comment by FailedShack** [comment]
@VelocityRa The problem is fixed when manually set to use the dedicated graphics card in the Nvidia control panel. The integrated graphics are fine, I prefer to have them render OS-related stuff and have the GPU fully available for more demanding tasks.

**Comment by jroweboy** [comment]
Its a pretty easy fix to tell the drivers to use the dedicated graphics card if someone wanted to PR that https://stackoverflow.com/a/39047129

**Comment by exjam** [comment]
I added the fix that jroweboy suggested, thanks.

https://github.com/decaf-emu/decaf-emu/commit/ca3ea69fde61cd5b899473789ad9b45eee07cbad
