### ISSUE TITLE
libraries/zlib-prefix/src/zlib-build/Debug/zlibd.lib', needed by 'obj/decaf-cli.exe', missing and no known rule to make it

### ISSUE THREAD

**Issue by BullyWiiPlaza** [decaf-emu/decaf-emu#481]
I imported the source code in `Visual Studio 2017` and when I try to build using `CMake` I'm getting the following error:
![image](https://user-images.githubusercontent.com/7620135/42723508-3631a4c8-875f-11e8-9986-e09484f6bceb.png)
How can this be fixed?

**Comment by baka0815** [comment]
All the entries in the ``libraries`` directory are git sub-modules. You need to fetch them too.

**Comment by BullyWiiPlaza** [comment]
@baka0815 I did. I cloned with `git clone --recursive` and then I also ran `git submodule update --init` but I still get the same compilation error.

The `zlib-prefix` folder does not exist:
![image](https://user-images.githubusercontent.com/7620135/42811696-b609ed00-89bb-11e8-8837-8183983d054e.png)

All sub modules have been fetched but I also don't see the `zlib-prefix` folder to be part of this repository either so I'm not sure if this isn't a configuration bug in the source code.

**Comment by VelocityRa** [comment]
IIRC you need to set `decaf-sdl` (or something like that) as the Start-up project, right click it in the Solution Explorer and you'll see the option.

**Comment by VelocityRa** [comment]
If that doesn't work try deleting the CMake caches (or just do `git clean -xfd` which will clear out everything that isn't in master) and generate the project files with cmake-gui.

**Comment by BullyWiiPlaza** [comment]
@VelocityRa I'm not sure how to do your first suggestion:
![image](https://user-images.githubusercontent.com/7620135/42821831-bdc1be24-89d9-11e8-95ca-1acfe0be95a1.png)
Your second message suggestions do not fix the problem.

**Comment by VelocityRa** [comment]
You shouldn't be in Folder View. Click the icon on the top, right of the Home icon and try it again.
