### ISSUE TITLE
Decaf Master Build Test Progress

### ISSUE THREAD

**Issue by EmulationChannel** [decaf-emu/decaf-emu#485]
![anotacao 1](https://user-images.githubusercontent.com/37957125/45247722-24864d80-b2e0-11e8-898b-ae2a6f209db0.png)
![anotacao 2](https://user-images.githubusercontent.com/37957125/45247723-251ee400-b2e0-11e8-80d9-da06854a55eb.png)
![anotacao 3](https://user-images.githubusercontent.com/37957125/45247725-251ee400-b2e0-11e8-8b77-286acf3055f1.png)
![anotacao 4](https://user-images.githubusercontent.com/37957125/45247726-251ee400-b2e0-11e8-9f0b-0b6747e79e56.png)
![anotacao 5](https://user-images.githubusercontent.com/37957125/45247727-251ee400-b2e0-11e8-846b-f465110641eb.png)
![anotacao 6](https://user-images.githubusercontent.com/37957125/45247728-25b77a80-b2e0-11e8-844e-8ee7186b0942.png)
![anotacao 7](https://user-images.githubusercontent.com/37957125/45247729-25b77a80-b2e0-11e8-92f8-57fbf8576c68.png)
![anotacao 8](https://user-images.githubusercontent.com/37957125/45247730-25b77a80-b2e0-11e8-8868-d11e5e70aaab.png)
![anotacao 9](https://user-images.githubusercontent.com/37957125/45247731-25b77a80-b2e0-11e8-965b-9e0ff2c9bba1.png)
![anotacao 10](https://user-images.githubusercontent.com/37957125/45247777-95c60080-b2e0-11e8-9e67-fed477538609.png)
![anotacao 11](https://user-images.githubusercontent.com/37957125/45247778-95c60080-b2e0-11e8-891d-9d19411e8ff3.png)
![anotacao 12](https://user-images.githubusercontent.com/37957125/45247779-95c60080-b2e0-11e8-9894-1d2ab6b6059a.png)
![anotacao 13](https://user-images.githubusercontent.com/37957125/45247780-95c60080-b2e0-11e8-81cf-ecc69c482dc4.png)
![anotacao 14](https://user-images.githubusercontent.com/37957125/45247789-a8d8d080-b2e0-11e8-89f2-45b50f4e6d8d.png)
![anotacao 15](https://user-images.githubusercontent.com/37957125/45247856-3ddbc980-b2e1-11e8-991d-46944c72c6fa.png)
![anotacao 16](https://user-images.githubusercontent.com/37957125/45247857-3ddbc980-b2e1-11e8-9278-df6de78c3c7f.png)
![anotacao 17](https://user-images.githubusercontent.com/37957125/45247858-3ddbc980-b2e1-11e8-80e9-5d025a839114.png)
![anotacao 18](https://user-images.githubusercontent.com/37957125/45247859-3ddbc980-b2e1-11e8-98f8-fa3ca1d0d615.png)
![anotacao 19](https://user-images.githubusercontent.com/37957125/45247860-3e746000-b2e1-11e8-93f6-c625816e564a.png)
https://ci.appveyor.com/project/exjam/decaf-emu/build/1.0.1803/artifacts

**Comment by CodingKoopa** [comment]
This isn't what GitHub issues are for. Issues are meant to track specific bugs, larger progress posts like this would be better for Reddit, YouTube, GBATemp, etc.
