### ISSUE TITLE
Implement OSFastMutex correctly

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#5]
For windows this is Windows8+ with WaitOnAddress.
For other platforms we can use futex.

**Comment by exjam** [comment]
This is different now we have a custom scheduler! Gotta read into this!

**Comment by exjam** [comment]
OSFastMutex currently falls back to OSMutex, however its functionality is different in that it attempts to lock the mutex using atomic CAS first, and only if the CAS fails does it fall back to using scheduler lock.

However OSFastMutex can still lead to thread test cancel and rescheduling, so the difference is only minor.

**Comment by brett19** [comment]
Completed by da32585b09665111ea3a66467b202169a2a9c2f6
