### ISSUE TITLE
Wait for the new Vulkan SDK and drivers.

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#502]
We require stream out / transform feedback which is a new extension in Vulkan not yet released in the official SDK installer or yet supported by released drivers. Although currently the nvidia beta driver has support and you can compile the Vulkan SDK yourself.

Once stream out is fully released we can remove the OpenGL backend and start building Vulkan in the CI builds. Until then OpenGL is treated as deprecated but will remain in the codebase and will be the only gpu driver in the CI builds.

**Comment by brett19** [comment]
I think the majority of the transform feedback interfaces are available now.  I think the only open issue is a SPIRV-Tools validation error w.r.t. the use of the SPIRV capability for transform feedback, which should be fixed quite soon.

**Comment by srdjan1995** [comment]
Does qt starts decaf in Vulkan by default, or we need to change from OGL to Vulkan? If so, how do I change it to Vulkan?

**Comment by EmulationChannel** [comment]
@srdjan1995 Change OpenGL API to Vulkan GPU API is simple navigate C: \ Users \ USER \ AppData \ Roaming \ decaf modify config.toml line use Notepad ++ or Sublime text modify (config.toml)

[display]
	backend = "onpegl"
	background_colour = [153, 51, 51]
	force_sync = false
	layout = "split"
	maintain_aspect_ratio = true
	mode = "windowed"
	split_seperation = 5.00000
	stretch = false
	view_mode = "split"

[display]
	backend = "vulkan"
	background_colour = [153, 51, 51]
	force_sync = false
	layout = "split"
	maintain_aspect_ratio = true
	mode = "windowed"
	split_seperation = 5.00000
	stretch = false
	view_mode = "split"

**Comment by Yvar192** [comment]
Translation:
Changing from the OpenGL graphics API to Vulkan is simple, navigate to `C:\%username&\Appdata\Roaming\decaf` In there you should find a file called `config.toml`
Change this:
```
[display]
backend = "onpegl"
```
To:
```
[display]
backend = "vulkan"
```
(I have no idea if this actually works, just trying to make EmulationChannel's comment more readable)

**Comment by Degerz** [comment]
Is it [almost](https://github.com/GPUOpen-Drivers/xgl/commit/6a629e8286ed9d2a8a3799131a274ee58590765d) time now to drop OpenGL ? Transform feedback will soon land in AMDVLK and will appear shortly thereafter in AMD's Windows Vulkan driver. The only major configuration left is Intel/Windows so will you proceed without them ?
