### ISSUE TITLE
Imput Keybord not  found Commands all GAMES 

### ISSUE THREAD

**Issue by EmulationChannel** [decaf-emu/decaf-emu#512]
![sharedscreenshot1](https://user-images.githubusercontent.com/37957125/50541562-b1a32a00-0b8f-11e9-9d22-46ba2d9abebd.jpg)
![sharedscreenshot2](https://user-images.githubusercontent.com/37957125/50541593-2bd3ae80-0b90-11e9-8b9a-a2a161bfdf0a.jpg)
![sharedscreenshot3](https://user-images.githubusercontent.com/37957125/50541615-b2888b80-0b90-11e9-93fd-d05c096b549f.jpg)

**Comment by exjam** [comment]
Keyboard input should work now on decaf-qt branch.
