### ISSUE TITLE
[Feature Request] Include standalone CLI shader decompiler

### ISSUE THREAD

**Issue by KillzXGaming** [decaf-emu/decaf-emu#520]
It would be nice to have a simple standalone tool for shader decompiling to assembly. gfd tool works fine for .gtx/gtx2 files, but i'd like to have one for decompiling raw binaries.

**Comment by brett19** [comment]
This should be relatively trivial to implement, especially since gfd-tool acts as a pretty good example.  Most components of decaf are relatively independant.

**Comment by exjam** [comment]
```
>gfd-tool.exe disassemble E:\test.bin
00 TEX: ADDR(16) CNT(1) VALID_PIX

  0      SAMPLE          R0.xyzw, R0.xy0x, t0, s0

01 EXP_DONE: PIX0, R0.xyzw

END_OF_PROGRAM
````
