### ISSUE TITLE
FSOpenFile - Invoking null dequeueCmdHandler

### ISSUE THREAD

**Issue by CreeperMario** [decaf-emu/decaf-emu#529]
After pulling master (`c364a01` as of earlier today) and rebasing #505 onto it, I found that the `filesystem_read` test was failing.

From `fsCmdQueueProcessCmd()` in `libdecaf/src/cafe/libraries/coreinit/coreinit_fs_cmdqueue.cpp`:

```
// Call the dequeue command handler
if (cafe::invoke(cpu::this_core::state(),
                 queue->dequeueCmdHandler,
                 cmd)) {
   return true;
}
```

Executing a callback like this seems pretty normal.

But what if `dequeueCmdHandler` is pointing to `0x0` in the PowerPC address space? Decaf will try to run code starting at `0x0`, triggering a PowerPC exception. (so `dequeueCmdHandler` was either never set to anything or was set to 0 after being set)

```
Core1 Instruction at 0x00000004 (value from SRR0) attempted to access invalid address 0x00000000 (value from DAR)
```

This occurs on the following line within the `filesystem_read` test:

```
status = FSOpenFile(&client, &cmdBlock, "/vol/content/short_text.txt", "r", &fh, -1);
```

**Comment by brett19** [comment]
I believe this is fixed now.
