### ISSUE TITLE
[Linux] Failed to load vulkan

### ISSUE THREAD

**Issue by KAMiKAZOW** [decaf-emu/decaf-emu#536]
When trying to run decaf-qt:

```
Failed to load vulkan: Cannot load library vulkan: (vulkan: cannot open shared object file: No such file or directory)
initInstance: No Vulkan library available
Failed to create platform Vulkan instance
Failed to create Vulkan instance: 0

```

Dolphin OTOH detects Vulkan just fine under Linux:
![screenshot_20190125_141956](https://user-images.githubusercontent.com/3259076/51748739-a3bcc800-20ad-11e9-9d04-59db073be8b3.png)

OS: openSUSE Tumbleweed, all updates incl. Qt 5.12.

**Comment by baka0815** [comment]
Do you have all vulkan drivers as 32 and 64-bit installed?

**Comment by Amnesia1000** [comment]
What Distro are you using?

**Comment by Amnesia1000** [comment]
Clarification, in case you didn't know, in linux compiles well, but does not start any game. It is already known to the developers, is very broken the emulator in Linux. Until one of the developers builds his linux PC we will not hear from Decaf on Linux.

**Comment by baka0815** [comment]
I'm getting a differnt output:
````
[info] Loaded config from /home/baka/.config/decaf/config.toml
terminate called after throwing an instance of 'vk::ExtensionNotPresentError'
  what():  vk::PhysicalDevice::createDevice: ErrorExtensionNotPresent
````
Using RADV (Mesa 18.3.2, AMD RX 580). The vulkan libraries can be found, but there seems to be an extension that's missing.

**Comment by Narann** [comment]
@baka0815 Since https://github.com/decaf-emu/decaf-emu/pull/557, you should be able to find which extension is missing.

**Comment by baka0815** [comment]
Well, I'm getting the following output using decaf-sdl:
````
[info] Loaded config from /home/baka/.config/decaf/config.toml
[error] Failed to create Vulkan graphics window
[error] Failed to initialise Vulkan backend.
Speicherzugriffsfehler        (english: access violation)
````

Using decaf-qt the output seems to suggest something different:
````
initResources
Assertion failed:
Expression: 0
File: /home/baka/svn/decaf/src/libgpu/src/vulkan/vulkan_validate.cpp
Line: 96
Message: Surface format 002[0](R4G4UnormPack8) does not support TransferDst feature

Ungültiger Maschinenbefehl        (english: invalid instruction)
````

**Comment by baka0815** [comment]
Ok, I remove the config file, created a new one and set the backend to vulkan and am now getting the same on SDL:
````
[info] Loaded config from /home/baka/.config/decaf/config.toml
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
Assertion failed:
Expression: 0
File: /home/baka/svn/decaf/src/libgpu/src/vulkan/vulkan_validate.cpp
Line: 96
Message: Surface format 002[0](R4G4UnormPack8) does not support TransferDst feature
````

**Comment by brett19** [comment]
This has been fixed as part of AMD which was also related to OSX support.

**Comment by brett19** [comment]
See #591
