### ISSUE TITLE
Only use 1 Vulkan graphics queue

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#538]
AMD usually only has 1 graphics queue, so we must refactor how we handle rendering to support this.

**Comment by Narann** [comment]
More information about queue family [here](https://www.reddit.com/r/vulkan/comments/46ckoc/queue_families/).

> From what I noticed:
> 
> * NVIDIA GPUs generally have 16 identical Queues (one queue family) that can do anything. I think these queues are multiplexed by the driver onto one actual hardware queue at drawcall boundaries.
> * AMD GPUs have 4+ queues of various families (one graphics/compute queue, 1-4 compute only queues and two transfer queues),
> * Intel GPUs **only have a single queue**.

**Comment by exjam** [comment]
Fixed with b2d18768bd6ba3caf4184525f5aefaae50c0adbb
