### ISSUE TITLE
[Linux] Vulkan | Surface format 002[0](R4G4UnormPack8) does not support TransferDst feature

### ISSUE THREAD

**Issue by barolo** [decaf-emu/decaf-emu#545]
Decaf fails to launch any game with this error:
"Assertion failed:
Expression: 0
File: ...decaf-emu/src/libgpu/src/vulkan/vulkan_validate.cpp
Line: 96
Message: Surface format 002[0](R4G4UnormPack8) does not support TransferDst feature"

AMD Vega [Raven APU] 
Mesa/Vulkan everything git/latest [ I'm on Gentoo ]

**Comment by exjam** [comment]
Please provide a vulkaninfo output.

Also beyond this there is still issue https://github.com/decaf-emu/decaf-emu/issues/538 preventing progress with AMD cards for now.

**Comment by paulguy** [comment]
I get the same error on an AMD Radeon RX 580.  Here's my vulkaninfo output.

https://gist.github.com/paulguy/559bd559e5ba65d381410b54ea0d189a

**Comment by brett19** [comment]
See #591
