### ISSUE TITLE
Can't build it…

### ISSUE THREAD

**Issue by greenvorbisfan** [decaf-emu/decaf-emu#547]
Ubuntu 18.04 x86_64 — can't build decaf. Log:
~/decaf-emu/src/libdecaf/src/cafe/libraries/cafe_hle.cpp:7:10: fatal error: dmae/dmae.h: Нет такого файла или каталога
 #include "dmae/dmae.h"
          ^~~~~~~~~~~~~
compilation terminated.
src/libdecaf/CMakeFiles/libdecaf.dir/build.make:535: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/src/cafe/libraries/cafe_hle.cpp.o' failed
make[2]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/src/cafe/libraries/cafe_hle.cpp.o] Error 1
make[2]: *** Ожидание завершения заданий…
CMakeFiles/Makefile2:708: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/all' failed
make[1]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by baka0815** [comment]
Did you clone the repository recursively?

**Comment by baka0815** [comment]
Looks like the same as #548.

**Comment by CodingKoopa** [comment]
Reposting from there: Most likely issue is that your compiler doesn't support C++17.

**Comment by greenvorbisfan** [comment]
What is `dmae.h`? How to find it?

**Comment by exjam** [comment]
Weird problem with your system? dmae exists at:

https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/cafe/libraries/dmae/dmae.h
