### ISSUE TITLE
Problem building, "No such file or directory"

### ISSUE THREAD

**Issue by dukenukemx** [decaf-emu/decaf-emu#548]
I get this error when building.  I'm using Linux Mint 19.1.  

In file included from /home/user/Downloads/decaf-emu/src/libdecaf/src/decaf.cpp:14:0:
/home/user/Downloads/decaf-emu/src/libdecaf/src/vfs/vfs_host_device.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
              ^~~~~~~~~~~~
compilation terminated.
src/libdecaf/CMakeFiles/libdecaf.dir/build.make:7685: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf.cpp.o' failed
make[2]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf.cpp.o] Error 1
CMakeFiles/Makefile2:749: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/all' failed
make[1]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CodingKoopa** [comment]
Most likely issue is that your compiler doesn't support C++17.

**Comment by dukenukemx** [comment]
So I need Clang 5 or GCC 8?  It seems I already have GCC 8 installed on Ubuntu.  When did that happen?

**Comment by snickerbockers** [comment]
Run gcc --version to confirm that's actually the version of gcc you're
using.  If you have more than one version of gcc installed then the latest
one might not be the one configured as the default.

**Comment by exjam** [comment]
More specifically you require std::filesystem - which is in gcc8.
