### ISSUE TITLE
Update Building to add qt5 libs

### ISSUE THREAD

**Issue by Narann** [decaf-emu/decaf-emu#555]
I needed `libqt5svg5-dev` to make `cmake` to work.

If others had other qt libs to provide, feel free to add them here.

I'm on Linux Mint 19.1.

**Comment by snickerbockers** [comment]
Ive found that in order to get it working on Linux I have to build QT from scratch because the official QT linux builds have Vulkan support disabled.

(although that's obviously QT's fault, not decaf's).

**Comment by Narann** [comment]
I use `-DDECAF_VULKAN=OFF` to make `cmake` works.

**Comment by exjam** [comment]
Fixed, note you no longer need Qt vulkan, but will need qtbase5-private-dev
