### ISSUE TITLE
[code] Useless if statements in Driver::drawGenericIndexed()

### ISSUE THREAD

**Issue by Narann** [decaf-emu/decaf-emu#560]
Looks like most (if not all) of the `if` statements are actually irrelevant as actual functions never `return false;`.

https://github.com/decaf-emu/decaf-emu/blob/master/src/libgpu/src/vulkan/vulkan_draw.cpp#L276

I can cleanup and provide a PR.

**Comment by brett19** [comment]
While many of them don't currently return false, they are left there for easier inclusion of ejection from the draw call if there is a failure to prepare one of the dependancies.  We use it a lot during debugging, and there are a few that we've left in.
