### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by nathanaelries** [decaf-emu/decaf-emu#563]
I have been having issues with the prebuilt package for libvpx. I try to build from sources and get an error about cygwin. Log included below.

`
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
silent=True
[build_requires]
[env]

Enabled dependencies:
ffmpeg/4.0.2@bincrafters/stable
libcurl/7.61.1@bincrafters/stable
OpenSSL/1.0.2n@conan/stable
sdl2/2.0.9@bincrafters/stable
zlib/1.2.11@conan/stable

Disabled dependencies:

conanfile.py: Installing package
Requirements
    OpenSSL/1.0.2n@conan/stable from 'conan-center' - Cache
    bzip2/1.0.6@conan/stable from 'conan-center' - Cache
    ffmpeg/4.0.2@bincrafters/stable from 'bincrafters' - Cache
    freetype/2.9.0@bincrafters/stable from 'conan-center' - Cache
    intel_media_sdk/2018R2@bincrafters/stable from 'bincrafters' - Cache
    lcms/2.9@bincrafters/stable from 'conan-center' - Cache
    libcurl/7.61.1@bincrafters/stable from 'conan-center' - Cache
    libfdk_aac/0.1.5@bincrafters/stable from 'conan-center' - Cache
    libiconv/1.15@bincrafters/stable from 'conan-center' - Cache
    libmp3lame/3.100@bincrafters/stable from 'conan-center' - Cache
    libpng/1.6.34@bincrafters/stable from 'conan-center' - Cache
    libtiff/4.0.9@bincrafters/stable from 'conan-center' - Cache
    libvpx/1.7.0@bincrafters/stable from 'bincrafters' - Cache
    libwebp/1.0.0@bincrafters/stable from 'conan-center' - Cache
    libx264/20171211@bincrafters/stable from 'conan-center' - Cache
    libx265/2.7@bincrafters/stable from 'bincrafters' - Cache
    lzma/5.2.3@bincrafters/stable from 'conan-center' - Cache
    ogg/1.3.3@bincrafters/stable from 'conan-center' - Cache
    openh264/1.7.0@bincrafters/stable from 'bincrafters' - Cache
    openjpeg/2.3.0@bincrafters/stable from 'conan-center' - Cache
    opus/1.2.1@bincrafters/stable from 'conan-center' - Cache
    sdl2/2.0.9@bincrafters/stable from 'bincrafters' - Cache
    vorbis/1.3.6@bincrafters/stable from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    OpenSSL/1.0.2n@conan/stable:d140711d95cc16a85766a8fc3a551dfafe84cf63 - Build
    bzip2/1.0.6@conan/stable:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
    ffmpeg/4.0.2@bincrafters/stable:9208d0dacf9004b59ce312004c15e4aeda9fa6da - Build
    freetype/2.9.0@bincrafters/stable:2eda287fd36b7b010dea069857045000246077e3 - Build
    intel_media_sdk/2018R2@bincrafters/stable:4068d26db0f235082dbcdd6f303d1cbf4d149cf1 - Cache
    lcms/2.9@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libcurl/7.61.1@bincrafters/stable:93789ffea161eae250e5428aea82b98d92a3244d - Build
    libfdk_aac/0.1.5@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libiconv/1.15@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libmp3lame/3.100@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
    libpng/1.6.34@bincrafters/stable:d140711d95cc16a85766a8fc3a551dfafe84cf63 - Build
    libtiff/4.0.9@bincrafters/stable:d140711d95cc16a85766a8fc3a551dfafe84cf63 - Download
    libvpx/1.7.0@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Build
    libwebp/1.0.0@bincrafters/stable:638042d3fd356128c913f5e725646a0c2af264c7 - Download
    libx264/20171211@bincrafters/stable:c448c6e76e3e7331394335260df94c64298aa1f6 - Build
    libx265/2.7@bincrafters/stable:c448c6e76e3e7331394335260df94c64298aa1f6 - Build
    lzma/5.2.3@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Build
    ogg/1.3.3@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Download
    openh264/1.7.0@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Build
    openjpeg/2.3.0@bincrafters/stable:e697f9d7742efe08749913700129b03f0134988e - Build
    opus/1.2.1@bincrafters/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Build
    sdl2/2.0.9@bincrafters/stable:1207f517a702731f7bcbfd9d309d0b8237719e8f - Download
    vorbis/1.3.6@bincrafters/stable:becff00909fb3d957c6b4ca60fa64d4e6a32a540 - Build
    zlib/1.2.11@conan/stable:3fb49604f9c2f729b85ba3115852006824e72cab - Download
Build requirements
    cygwin_installer/2.9.0@bincrafters/stable from 'conan-center' - Cache
    msys2_installer/20161025@bincrafters/stable from 'conan-center' - Cache
    nasm_installer/2.13.02@bincrafters/stable from 'conan-center' - Cache
    ninja_installer/1.8.2@bincrafters/stable from 'conan-center' - Cache
    strawberryperl/5.26.0@conan/stable from 'conan-center' - Cache
    yasm_installer/1.3.0@bincrafters/stable from 'conan-center' - Cache
Build requirements packages
    cygwin_installer/2.9.0@bincrafters/stable:82225602131907b10527ab10c22bdd1c3b7edf72 - Cache
    msys2_installer/20161025@bincrafters/stable:3cbd862cb7a3ea47ed1220dc027f344262d5224f - Cache
    nasm_installer/2.13.02@bincrafters/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Download
    ninja_installer/1.8.2@bincrafters/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Download
    strawberryperl/5.26.0@conan/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Download
    yasm_installer/1.3.0@bincrafters/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Cache

bzip2/1.0.6@conan/stable: Already installed!
cygwin_installer/2.9.0@bincrafters/stable: Already installed!
cygwin_installer/2.9.0@bincrafters/stable: Creating CYGWIN_ROOT env var : C:\.conan\8500a8\1
cygwin_installer/2.9.0@bincrafters/stable: Creating CYGWIN_BIN env var : C:\.conan\8500a8\1\bin
cygwin_installer/2.9.0@bincrafters/stable: Appending PATH env var with : C:\.conan\8500a8\1\bin
intel_media_sdk/2018R2@bincrafters/stable: Already installed!
lcms/2.9@bincrafters/stable: Already installed!
libfdk_aac/0.1.5@bincrafters/stable: Already installed!
libiconv/1.15@bincrafters/stable: Already installed!
libmp3lame/3.100@bincrafters/stable: Already installed!
libvpx/1.7.0@bincrafters/stable: Copying sources to build folder
libvpx/1.7.0@bincrafters/stable: Building your package in C:\Users\Admin\.conan\data\libvpx\1.7.0\bincrafters\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab
libvpx/1.7.0@bincrafters/stable: Generator txt created conanbuildinfo.txt
libvpx/1.7.0@bincrafters/stable: Calling build()
libvpx/1.7.0@bincrafters/stable: 
WARN: libcurl/7.61.1@bincrafters/stable requirement OpenSSL/1.1.1c@conan/stable overridden by  to OpenSSL/1.0.2n@conan/stable
libvpx/1.7.0@bincrafters/stable: WARN: Package is corrupted, removing folder: C:\Users\Admin\.conan\data\libvpx\1.7.0\bincrafters\stable\package\3fb49604f9c2f729b85ba3115852006824e72cab
libvpx/1.7.0@bincrafters/stable: WARN: Build folder is dirty, removing it: C:\Users\Admin\.conan\data\libvpx\1.7.0\bincrafters\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab
libvpx/1.7.0@bincrafters/stable: ERROR: Package '3fb49604f9c2f729b85ba3115852006824e72cab' build failed
libvpx/1.7.0@bincrafters/stable: WARN: Build folder C:\Users\Admin\.conan\data\libvpx\1.7.0\bincrafters\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab
ERROR: libvpx/1.7.0@bincrafters/stable: Error in build() method, line 39
        cygwin_bin = self.deps_env_info['cygwin_installer'].CYGWIN_BIN
        KeyError: 'cygwin_installer'
`

**Comment by exjam** [comment]
Try adding `-s compiler.version=15` to your conan install arguments to force it to grab vs2017 builds of dependenices, I think most packages are not yet built for vs2019 and it is trying to make you build them locally.
