### ISSUE TITLE
Report TRAVIS_BUILD_DIR/build Compile sdl2/2.0.9@bincrafters/stable: ERROR Linux OS

### ISSUE THREAD

**Issue by emulationchannel** [decaf-emu/decaf-emu#568]
sdl2/2.0.9@bincrafters/stable: ERROR: while executing system_requirements(): Command 'sudo apt-get install -y --no-install-recommends libegl1-mesa-dev:amd64' failed
ERROR: Error in system requirements
The command "cd "$TRAVIS_BUILD_DIR/build"; conan install .. --build=missing -s compiler=$CONAN_COMPILER -s compiler.version=$CONAN_COMPILER_VERSION -o silent=True -o curl=False -o openssl=False -o ffmpeg=False" failed and exited with 1 during .

**Comment by dracc** [comment]
What OS are you using? Is your user in the sudoers file/sudo group?

**Comment by emulationchannel** [comment]
Windows OS https://travis-ci.org/decaf-emu/decaf-emu/jobs/588392423

**Comment by exjam** [comment]
We are now using Github Actions.
