### ISSUE TITLE
Ci.Appveyor Build Failed  (60 minutes). Reset Appveyor

### ISSUE THREAD

**Issue by emulationchannel** [decaf-emu/decaf-emu#569]
Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by dracc** [comment]
Where do you see this error? Your PR only shows errors about unresolved externals as far as I can tell.

**Comment by emulationchannel** [comment]
https://ci.appveyor.com/project/exjam/decaf-emu/builds/27537015/messages

**Comment by dracc** [comment]
```

Downloading conan_package.tgz
Please log in to "conan-center" to perform this action. Execute "conan user" command.
If you don't have an account sign up here: https://bintray.com/signup/oss
Remote 'conan-center' username:```

**Comment by emulationchannel** [comment]
[log.txt](https://github.com/decaf-emu/decaf-emu/files/3654491/log.txt)

**Comment by dracc** [comment]
Yes, except that log of yours is missing the last line, 688.
https://ci.appveyor.com/project/exjam/decaf-emu/builds/27537015#L688

**Comment by emulationchannel** [comment]
Downloading conan_package.tgz
Please log in to "conan-center" to perform this action. Execute "conan user" command.
If you don't have an account sign up here: https://bintray.com/signup/oss
Remote 'conan-center' username:

**Comment by dracc** [comment]
...yes?

**Comment by emulationchannel** [comment]
yes conan erro download

**Comment by exjam** [comment]
We are now using Github Actions.
