### ISSUE TITLE
Get started with GitHub Package Registry Add Decaf-Emu 

### ISSUE THREAD

**Issue by emulationchannel** [decaf-emu/decaf-emu#570]
![SharedScreenshot](https://user-images.githubusercontent.com/54820827/65516311-2f922880-deb7-11e9-8537-7ed60bd7a9b7.jpg)

**Comment by CodingKoopa** [comment]
The Package Registry is for publishing packages, which isn't really applicable to Decaf. The only potential use case would be for publishing a no-graphics Decaf Docker image, which doesn't exist (and there wouldn't really be much of a use for that itself, except for homebrew CI perhaps.).

**Comment by exjam** [comment]
I do not think we have any use for the Github Package Registry.
