### ISSUE TITLE
[Linux] TransferDst progress

### ISSUE THREAD

**Issue by Devorlon** [decaf-emu/decaf-emu#572]
Hi,

I was wondering if any progress had been made on allowing AMD cards to run Decaf (in my case under Linux).

This issue is the same as [#545](https://github.com/decaf-emu/decaf-emu/issues/545) and is similar to [#536](https://github.com/decaf-emu/decaf-emu/issues/536).

Spec:

Arch Linux
Kernel 5.3
Vulkan 1:19.3.0_devel.115908.6309c31fd81-1
RX 5700 XT

The error is:

[usr@usr obj]$ ./decaf-qt 
WARNING: radv is not a conformant vulkan implementation, testing use only.
initResources
Assertion failed:
Expression: 0
File: /home/usr/programs/decaf-emu/src/libgpu/src/vulkan/vulkan_validate.cpp
Line: 95
Message: Surface format 002(0)(R4G4UnormPack8) does not support TransferDst feature
�
Aborted (core dumped)

**Comment by paulguy** [comment]
Doesn't work with amdvlk either.
```
 $ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json build/obj/decaf-qt 
terminate called after throwing an instance of 'vk::ExtensionNotPresentError'
  what():  vk::PhysicalDevice::createDevice: ErrorExtensionNotPresent
zsh: abort (core dumped)  VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json build/obj/decaf-qt
```

**Comment by brett19** [comment]
I mean... That first error from @Devorlon is saying that it doesn't support uploading textures to a surface, which is obviously an issue...  It's probably specific to R4G4UnormPack8, and someday we may implement an internal conversion to handle it, but its not going to be a priority in the near future.  The second error from @paulguy is a bit unclear, sort of unfortunate that it's not printing the extension we asked for that it doesn't support.  I've listed the extensions we use below, it would be great if you can compare against the gpuopen information for your system and see what's missing:

KHR_GET_PHYSICAL_DEVICE_PROPERTIES_2 - dependancy for TRANSFORM_FEEDBACK below
KHR_SWAPCHAIN - required by everything
KHR_MAINTENANCE1 - required by Decaf
KHR_PUSH_DESCRIPTOR - not required, but probably not the cause
KHR_STORAGE_BUFFER_STORAGE_CLASS - not required, but probably not the cause
EXT_TRANSFORM_FEEDBACK - required for WiiU
EXT_VERTEX_ATTRIBUTE_DIVISOR - required for WiiU
EXT_DEPTH_RANGE_UNRESTRICTED - required for WiiU

**Comment by paulguy** [comment]
According to vulkaninfo, VK_KHR_push_descriptor is what was missing.  After commenting out the item in createDevice, it seems to continue further but runs in to another, different TransferDst error:
```
 $ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json build/obj/decaf-qt
Assertion failed:
Expression: 0
File: /home/paul/decaf-emu/src/libgpu/src/vulkan/vulkan_validate.cpp
Line: 95
Message: Surface format 011[0](D24UnormS8Uint) does not support TransferDst feature

zsh: abort (core dumped)  VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json build/obj/decaf-qt
```

**Comment by brett19** [comment]
This will be tracked under #591 (which is the actual fix needing to be made).
