### ISSUE TITLE
linux build failed

### ISSUE THREAD

**Issue by lgczszs** [decaf-emu/decaf-emu#580]
In file included from /media/universe/DA18EBFA09C1B27D/decaf-emu/src/libdecaf/src/decaf.cpp:14:0:
/media/universe/DA18EBFA09C1B27D/decaf-emu/src/libdecaf/src/vfs/vfs_host_device.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
src/libdecaf/CMakeFiles/libdecaf.dir/build.make:4878: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf.cpp.o' failed
make[2]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf.cpp.o] Error 1
make[2]: *** 
CMakeFiles/Makefile2:991: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/all' failed
make[1]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

/decaf-emu/src/libdecaf/src/decaf_slc.cpp:9:10: fatal error: filesystem: No such file or directory #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
src/libdecaf/CMakeFiles/libdecaf.dir/build.make:4983: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf_slc.cpp.o' failed
make[2]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf_slc.cpp.o] Error 1
compilation terminated.
src/libdecaf/CMakeFiles/libdecaf.dir/build.make:4878: recipe for target 'src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf.cpp.o' failed
make[2]: *** [src/libdecaf/CMakeFiles/libdecaf.dir/src/decaf.cpp.o] Error 1

**Comment by exjam** [comment]
What compiler are you using and what version is it?

**Comment by exjam** [comment]
This just means you're missing [std::filesytem](https://en.cppreference.com/w/cpp/header/filesystem)

**Comment by lgczszs** [comment]
What I use is ubuntu 18.0.4

**Comment by dracc** [comment]
@lgczszs That's the distro. What does `gcc --version` output?

**Comment by lgczszs** [comment]
gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by exjam** [comment]
Seems like gcc does not support <filesystem> until gcc-8.

I have updated BUILDING.md to reflect that.

You can install gcc-8 or gcc-9 by following this: https://askubuntu.com/a/1087116
