### ISSUE TITLE
[Linux] Decaf no longer builds

### ISSUE THREAD

**Issue by Shoegzer** [decaf-emu/decaf-emu#581]
Decaf no longer builds on linux, testing against commit 8579bf62d32e80c64ce1f172e1fa3800c9926934.  This used to compile without error, though the last compilation time was Oct. 29, 2018. 

Complete cmake/build log is [here](https://pastebin.com/2L2MuDHz)

Test system is linux mint 19.2, kernel 5.0 and gcc 9.2.1.

**Comment by Kinnay** [comment]
This should be fixed with commit [5a9ec71](https://github.com/decaf-emu/decaf-emu/commit/5a9ec714c47e046f905249eba4bfc24d83123b29).

**Comment by exjam** [comment]
Thanks Kinnay for fixing this,

**Comment by Shoegzer** [comment]
Indeed, thanks @Kinnay.  I discovered another compile-time error but I'll post a separate issue for it.
