### ISSUE TITLE
[Linux] Decaf won't build

### ISSUE THREAD

**Issue by Shoegzer** [decaf-emu/decaf-emu#587]
Testing against commit b26df065b42adf326fb0ce666b5f85864bfe4e5f. This used to compile without error, though the last successful compilation time was Oct. 29, 2018.

Complete cmake/build log is [here](https://pastebin.com/7dgaCbqa)

Test system is linux mint 19.2, kernel 5.0 and gcc 9.2.1.

**Comment by Kinnay** [comment]
Your Qt version is old. QFontMetrics::horizontalAdvance was added in Qt 5.11. See https://stackoverflow.com/questions/50864893/qts-qfontmetricshorizontaladvance-missing-for-code-editor-implementation. 

I got the same error when I installed Qt through apt (like explained by BUILDING.md), but after installing Qt 5.12 with the official installer from the Qt website it worked.

**Comment by Shoegzer** [comment]
Ah yes, that makes sense, thanks.  Actually I've already installed Qt 5.11 via repo and sometimes run `source /opt/qt511/bin/qt511-env.sh` when compiling against the new Qt is needed, just hadn't needed it for the decaf project until recently I suppose.  After doing that, it works fine.  Closing this.
