### ISSUE TITLE
[Linux] Games launch from decaf-qt into debugger

### ISSUE THREAD

**Issue by Shoegzer** [decaf-emu/decaf-emu#588]
Games launch into the debugger and don't go ingame.  Marking this as a Linux-only issue because games such as [these](https://www.youtube.com/watch?v=U4A8M5TxIQI) can be seen going ingame from decaf-qt on Windows.

Tested on linux mint 19.2, kernel 5.0 compiled using gcc 9.2.1 with `cmake -DCMAKE_BUILD_TYPE=Release `

**Comment by exjam** [comment]
Do you have break_on_entry set? (Or in decat qt I think its under debugger settings > break on entry)

The debugger opens when the game hits a breakpoint or crashes.

**Comment by Shoegzer** [comment]
Thanks @exjam, I guess it's "break on main entry point" and no, that wasn't set.  I only had "break on exit" set but that shouldn't matter (I turned it off regardless and encountered the same issue).  Could decaf-qt be ignoring the setting perhaps?

**Comment by Kinnay** [comment]
Does the log say anything useful? I just tried to run SM3DW myself and it launched the debugger because of a crash. Maybe the same thing is happening on your machine.

**Comment by exjam** [comment]
I'd keep break on exit enabled as it lets you know a game has exited rather than is loading/hung.

Sounds like games are crashing for you, maybe you are testing with games which require the Mii files (FFLResHigh.dat etc)? There are plenty of guides around online for getting these files as Cemu would also require them.

Also seeing as this is bug is probably games crashing I can't help diagnose the issue further without logs, enable logging to file and upload the logs.  I have played SM3DW + NES Remix on my Linux laptop in decaf-emu before so I know it is possible - unless there has been a recent regression which broke things.

**Comment by Shoegzer** [comment]
Thanks, both of you.  I should note that I move the contents of build/obj to a separate directory and run dolphin-qt from there.  Running this in commandline yields:

> $ ./decaf-qt 
> QIODevice::read (QFile, ":ads/stylesheets/default_linux.css"): device not open
> 

Though I doubt that's related to decaf nor is it necessarily an error condition.

Rather, [here](https://hastebin.com/kodeyofiwo.sql) is a log of a session where SM3DW is launched from decaf-qt, which hopefully sheds more light.

**Comment by Kinnay** [comment]
Yeah I got the same crash. I think it's a bug in decaf's filesystem code again. SM3DW crashes when it tries to use ShaderData/RenderMaterialCloud.szs, shortly after calling FSReadDir on the ShaderData folder a few times.

**Comment by Shoegzer** [comment]
Thanks, at least it appears to be a legitimate issue and not something on this end but I'm happy to help test anything towards a fix.

**Comment by brett19** [comment]
We used std::filesystem to try and resolve some platform-specific differences, turns out it just caused new ones because std::filesystem isn't as beautiful of an abstraction as one might expect... :D

**Comment by exjam** [comment]
Super Mario 3D World should now work on Linux because of these two commits: 
https://github.com/decaf-emu/decaf-emu/commit/b26df065b42adf326fb0ce666b5f85864bfe4e5f
https://github.com/decaf-emu/decaf-emu/commit/1474e054fc8bfdd4622e98f713d146f8e5b22512

Thanks to @Kinnay for finding both issues

**Comment by Shoegzer** [comment]
Tested and working fine here now.  Thanks all and especially @Kinnay for your help and fix.
