### ISSUE TITLE
decaf-qt: Can't launch title with space in argstr

### ISSUE THREAD

**Issue by Kinnay** [decaf-emu/decaf-emu#593]
I noticed this when I tried to launch AOC Overlay App from the title list.

There's a space behind the filename in its cos.xml:
`<argstr type="string" length="4096">mintU.rpx </argstr>`

Decaf fails with the following error message because std::filesystem::is_regular_file returns false (std::filesystem::status returns std::filesystem::file_type::not_found):
`[17:25:53.108498 error:decaf] Could not find valid application at mlc/sys/title/00050030/1001a10a/code/mintU.rpx`

If I remove the space in argstr it works fine.

I also noticed that there are spaces elsewhere in the file. For example:

```
   <p0 type="complex">
      <group type="unsignedInt" length="4"> 1</group>
      <mask type="hexBinary" length="8">000000000000FF00</mask>
    </p0>
```

I don't know if this can cause any issues in decaf, but it might be something you'd want to check.

**Comment by exjam** [comment]
Interestingly this still worked on Windows (my cos.xml for that title also has the spaces), I pushed a fix to trim the fields when read from decaf-qt.

Also, I checked and pugixml is correctly skipping the spaces when parsing numbers out of xml text:
```
		while (PUGI__IS_CHARTYPE(*s, ct_space))
			s++;
```

The only place we might have an issue is in HexBinary as we parse that ourselves, so I trimmed that to be sure:
https://github.com/decaf-emu/decaf-emu/commit/283d223f7536806a09be8830caaa11d3671d211b

Thanks!

**Comment by Kinnay** [comment]
Looks like the issue is only fixed partially. I get the following error now:

`[10:01:14.661273 error:p1 tFF] ***Loader failure -196631 first time, -196631 second time and -196631 third time. loading "mintU.rpx ".`

**Comment by exjam** [comment]
Ah ok, looking at MXML source it seems it left trims whitespace even from strings:
https://github.com/michaelrsweet/mxml/blob/f166ad1977f2f13295689772a5d9e442f73d46f1/mxml-get.c#L356

Tbh we should probably just move to MXML, which is what IOS uses, as pugixml cannot read sysprod.xml (see #530), for now though i will trim strings read from XML also.
