### ISSUE TITLE
GX2TVScanMode seems to be wrong

### ISSUE THREAD

**Issue by Clownacy** [decaf-emu/decaf-emu#597]
I was having some problems writing homebrew using WUT, which [got its `GX2TVScanMode` enum from this project](https://github.com/devkitPro/wut/commit/e89da7a2166ecce21c0448878a2ba85cfd000497).

After testing `GX2GetSystemTVScanMode` on real hardware, I noticed your values seem to be off-by-one. After looking at other projects, I found there's an extra value that goes before 480i - 576i.

WUT issue:
https://github.com/devkitPro/wut/issues/119

**Comment by exjam** [comment]
Thanks for reporting this.
