### ISSUE TITLE
Investigate MCP_* and UC*

### ISSUE THREAD

**Issue by exjam** [decaf-emu/decaf-emu#6]
Start by testing these functions on a real WiiU and see what happens!

**Comment by crediar** [comment]
I can do that.

**Comment by exjam** [comment]
Yeah, basically want to figure out the data structures returned from MCP_GetSysProdSettings and UCReadSysConfig.

Marionumber1 had mentioned you knew a bit about MCP_GetSysProdSettings!

**Comment by exjam** [comment]
We should probably add a proper key/value store rather than if statement for user config.
