### ISSUE TITLE
Recent Decaf builds are crashing / freezing

### ISSUE THREAD

**Issue by Shoegzer** [decaf-emu/decaf-emu#611]
Launching recent builds of Decaf and then running any game results in a crash with the following thrown to terminal:
```
terminate called after throwing an instance of 'vk::OutOfDateKHRError'
  what():  vk::Queue::presentKHR: ErrorOutOfDateKHR
Aborted (core dumped)
```
Had time to perform a bisect on this, results are below. @QuarkTheAwesome if you have any resources to help, i'm happy to provide any other information you may need.

**Test Info**:
* OS: Linux Mint 20.1 / kernel 5.8
* CPU: Intel i7-7820HK
* GPU: Nvidia GTX-1070M / driver 460.32
* Compiler: gcc 10.2.0
* Bisect bad commit: 131aeb14fccff8461a5fd9f2aa5c040ba3880ef5

**Comment by QuarkTheAwesome** [comment]
ow. Which vulkan SDK version are you using? I just ran a quick test build on whatever the latest from lunarg's apt is (`1.2.162.1~rc4-1lunarg20.04`, mesa `20.2.6`) and it worked fine. If you haven't got any ppas or custom repos set up it's likely too old. The issue could also stem from the Nvidia proprietary driver - I only have AMD cards to test on - though by my understanding the ABI on that low of a level is all C anyway and therefore can't throw exceptions.
The other thing I'm wondering about is that the [vulkan.hpp README](https://github.com/KhronosGroup/Vulkan-Hpp#return-values-error-codes--exceptions) says a special #define needs to be set for noexcept to happen, which is very much not the behavior I observed while writing that commit.

Quietly hopeful it's just an out-of-date vulkan issue and we don't end up in the awkward situation where functions marked noexcept do sometimes throw depending on the underlying driver.

**Comment by Shoegzer** [comment]
@QuarkTheAwesome Thank you for your thoughts and assistance.  I was using Vulkan SDK 1.2.148 so I used apt upgrade to upgrade to the latest (specifically `1.2.162.0-1lunarg20.04-1`)  Unfortunately it's still crashing though, with the same message as posted above.

**Comment by QuarkTheAwesome** [comment]
Did you do a full make clean/rebuild? Some distros are set up to not recompile files even if the underlying libraries change. If that doesn't fix it, we may have to look at enabling the noexcept #define, which could easily break other vulkan things if we're not careful...
If you're able to run decaf under gdb and get a backtrace too that could be helpful, at least to understand where these exceptions are coming from.

**Comment by Shoegzer** [comment]
Yes it was a clean build, from a new source path.

Just let me know how to enable the noexcept #define and I'll do that for you, it wasn't clear to me from the above link though I'm guessing I would need to re-compile the vulkan-hpp with this option.  

In the meantime, here's a [gdb backtrace](https://pastebin.com/9ucTKEsg) for you.

**Comment by Shoegzer** [comment]
Update: After updating my system and all libraries, I recompiled and tested Decaf.  It's no longer crashing, however it won't load games either. Here is a log of what I see when I run decaf-qt from terminal and attempt to launch a game:
Loading Decaf:
```
$ ./decaf-qt
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QObject::connect: No such slot MainWindow::toggleFullScreen()
QObject::connect:  (sender name:   'actionViewFullScreen')
QObject::connect:  (receiver name: 'MainWindow')
```
Launching game:
```
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 850, resource id: 127926309, major code: 149 (Unknown), minor code: 4
```
Note that the last line repeats 10 times and then stops, and Decaf freezes before launching the game.

**Comment by QuarkTheAwesome** [comment]
@Shoegzer in `~/.config/decaf/config.toml`, the `[log]` section, can you set `to_stdout` to `true` and `level` to... idk, `"debug"` and try again? You'll wanna pipe it into a file, but hopefully will provide a little more insight than "driver no likey"

**Comment by Shoegzer** [comment]
@QuarkTheAwesome wow you weren't kidding - lots more info now, take a look [here](https://pastebin.com/iG619cy5).  Any clues?  To me it looks like some kind of opengl/mesa issue but I'm not sure.

**Comment by QuarkTheAwesome** [comment]
Hrm, not much out of the ordinary to my eye, those messages at the start are pretty normal for non-NVIDIA cards
I wonder if it's just Intel's Vulkan drivers being a bit questionable? I haven't used them for a while, may have to dig out the ol' Ivy Bridge rig haha

**Comment by Shoegzer** [comment]
@QuarkTheAwesome Thanks.. but.. this test system has both an Intel and nvidia (gtx 3070m) gpu. I wonder why it's finding/preferring the Intel gpu?  Any way to force it?

**Comment by QuarkTheAwesome** [comment]
You said as much in your initial post, too. I'm very good at reading.
maybe run `vulkaninfo` and post the output? Should show if the nvidia proprietary stuff is even detected. (the FOSS nvidia drivers have no vulkan support iirc, therefore they can't run Decaf)

**Comment by Shoegzer** [comment]
Haha no worries my man, actually my test system has changed somewhat since my OP (3070 now vs. 1070 but still nvidia).  

Click [here](https://pastebin.com/kFu76DEM) for juicy bits.  Of note:
```
VkPhysicalDeviceDriverProperties:
---------------------------------
	driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
	driverName         = NVIDIA
	driverInfo         = 460.39
	conformanceVersion = 1.2.4.0
```

**Comment by curtisy1** [comment]
Sorry to butt in so suddenly but after reading this I believe I found myself in a similar situation before. At least the part where the Intel iGPU is used instead of the discrete one sounds closely familiar (also hey @QuarkTheAwesome been a while!).

It's also been a while since I got to play around with decaf but looking at [choosePhysicalDevice](https://github.com/decaf-emu/decaf-emu/blob/master/src/libgpu/src/vulkan/vulkan_display.cpp#L248) it currently chooses the first vulkan-capable GPU no matter what.

What's interesting is that the NVIDIA dGPU seems to be the first vulkan-capable GPU in your configuration so in theory it _should_ use that by default.

What you could try is setting `DRI_PRIME=0` before running decaf or alternatively modifying choosePhysicalDevice so that it prefers choosing the dGPU (something like this, excuse my C++)
```
static vk::PhysicalDevice
choosePhysicalDevice(vk::Instance &instance)
{
   auto physicalDevices = instance.enumeratePhysicalDevices();

   // Try to find a device that has a discrete GPU
   for (size_t i = 0; i < physicalDevices.size(); i++) {
      auto device{ physicalDevices[i] };
      auto deviceProperties{ device.getProperties() };

      if (deviceProperties.deviceType == vk::PhysicalDeviceType::eDiscreteGpu) {
         return device;
      }
   }

   return physicalDevices[0];
}
```

I hope this is at least a little helpful

**Comment by Shoegzer** [comment]
Thanks for your help @curtisy1 !  

So I tried `export DRI_PRIME=0` before running decaf from terminal but same issue unfortunately.  Is that what you had in mind?  If it is, then i'll try your other suggestion and recompile.

**Comment by QuarkTheAwesome** [comment]
I did note that the INTEL-MESA message is also listed in the vulkaninfo, which might suggest that gets printed when the vulkan drivers are loaded - regardless of if the GPU actually gets used. Might be a red herring? Though it does seem odd that such a modern GPU wouldn't support all the requisite Vulkan features.

**Comment by curtisy1** [comment]
> So I tried export DRI_PRIME=0 before running decaf from terminal

Yup, that's what I meant. Out of curiosity, could you run `vkcube` with the `--gpu-number` flag set to 0 (for nvidia) and 1 (for intel) respectively and see if they both work?

**Comment by Shoegzer** [comment]
Done.  Actually --gpu_number 0 reports intel, and 1 reports nvidia.  When I run with 0 I get a black screen, and with 1 I get the rapidly-spinning cube.  Here's a log from term:
```
$ vkcube --gpu_number 0
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Selected GPU 0: Intel(R) UHD Graphics (CML GT2), type: 1

$ vkcube --gpu_number 1
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Selected GPU 1: GeForce RTX 3070 Laptop GPU, type: 2
```

**Comment by Shoegzer** [comment]
Also, I realize this is mostly information I posted above, but so it's in once place: here's what happens in terminal when I `export DRI_PRIME=0`:
```
$ ./decaf-qt 
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QObject::connect: No such slot MainWindow::toggleFullScreen()
QObject::connect:  (sender name:   'actionViewFullScreen')
QObject::connect:  (receiver name: 'MainWindow')
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 689, resource id: 119537698, major code: 149 (Unknown), minor code: 4
```
Ahd here's with `export DRI_PRIME=1
````

$ ./decaf-qt 
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
QObject::connect: No such slot MainWindow::toggleFullScreen()
QObject::connect:  (sender name:   'actionViewFullScreen')
QObject::connect:  (receiver name: 'MainWindow')
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

terminate called after throwing an instance of 'vk::OutOfDateKHRError'
  what():  vk::Queue::presentKHR: ErrorOutOfDateKHR
Aborted (core dumped)
```

**Comment by curtisy1** [comment]
> Actually --gpu_number 0 reports intel, and 1 reports nvidia

Sorry, my bad. Of course the iGPU is usually the primary GPU even though vulkaninfo assigns it to id 0 so this makes sense. 
What I'm surprised about is that the nvidia still gives you the `BadDrawable` even though it's used explicitly.

If you have a `/usr/share/vulkan/icd.d` directory, could you run `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json ./decaf-qt` and see if this works? Alternatively `DRI_PRIME=0 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json ./decaf-qt` would be worth a try too (though they should behave the same way)

That's pretty much the last idea that comes to mind without having to apply the [patch above](https://github.com/decaf-emu/decaf-emu/issues/611#issuecomment-817292439) and recompiling decaf

**Comment by Shoegzer** [comment]
Thanks @curtisy1 

Results are below, and pretty much the same unfortunately.  I'll try recompiling next, but before I do, one more question: has Decaf been tested against Vulkan 1.2.170 as posted [here](https://packages.lunarg.com/)?  I upgraded my system recently and installed this SDK, so just making sure it isn't that.
```
$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json ./decaf-qt
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
SDL_CONTROLLERDEVICEADDED
terminate called after throwing an instance of 'vk::OutOfDateKHRError'
  what():  vk::Queue::presentKHR: ErrorOutOfDateKHR
Aborted (core dumped)

$ DRI_PRIME=0 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json ./decaf-qt
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
SDL_CONTROLLERDEVICEADDED
terminate called after throwing an instance of 'vk::OutOfDateKHRError'
  what():  vk::Queue::presentKHR: ErrorOutOfDateKHR
Aborted (core dumped)
```

**Comment by curtisy1** [comment]
Sorry for the delayed reply @Shoegzer 

> has Decaf been tested against Vulkan 1.2.170

Unfortunately, I cannot test this at the moment since I'm still running 1.2.162 and the distro I use (Solus) doesn't yet have any update to 1.2.170 available. I'll try to package it myself over the weekend but you'd probably be faster with recompiling decaf in the meantime

**Comment by Shoegzer** [comment]
No worries @curtisy1.  I just recompiled with your mod suggestion to `static vk::PhysicalDevice` but got the same results unfortunately:
```
$ ./decaf-qt 
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
SDL_CONTROLLERDEVICEADDED
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

terminate called after throwing an instance of 'vk::OutOfDateKHRError'
  what():  vk::Queue::presentKHR: ErrorOutOfDateKHR
Aborted (core dumped)
```

**Comment by curtisy1** [comment]
Okay so after rebuilding my vulkan version manually to test against 1.2.170, it seems this is indeed an issue since I am now also getting the `ErrorOutOfDateKHR`.

Oddly enough it seems to work when using decaf-sdl. Maybe you could try using that and see if it works?

**Comment by Shoegzer** [comment]
Well that's "good" in a sense that at least it's reproduceable and I'm not losing my mind :)

Still, I tried with `$ ./decaf-sdl play <game>.wux `but the game doesn't launch.  Here's the console log:  
```
[info] Loaded config from /home/shoegzer/.config/decaf/config.toml
[info] Using SDL video driver x11
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[error] Failed to start game
terminate called without an active exception
Aborted (core dumped)
```

**Comment by curtisy1** [comment]
I don't think decaf supports .wux files (yet). At least there's an [open issue](https://github.com/decaf-emu/decaf-emu/issues/378) about it

**Comment by Shoegzer** [comment]
Ah right, sorry.  I have decaf-qt pointed at a different top-level dir and it finds the games (looks like it finds the .apx files).  However, I tried using different paths and it didn't work.  What game path does dolphin-sdl look for generally?

**Comment by curtisy1** [comment]
I might be wrong about this, so maybe @QuarkTheAwesome could correct me if I'm talking nonsense. Generally speaking both decaf-qt and decaf-sdl look for a path that contains `cos.xml` in either `current_path/code/`, `current_path/data/code` if the path you specified is a directory. If it isn't (i.e. you directly selected a .rpx or .wux, it looks for the `cos.xml` at `../code`. If such path is found, it gets mounted to `/vol/code`, `/vol/content` and `/vol/meta`. If it doesn't exist, decaf checks if the file ends with .rpx and mounts the directory the .rpx resides in as `/vol/code`. It also mounts `/vol/content` to a directory you specify in the `config.toml` in that case.

The difference between sdl and qt here is that sdl exits when neither cos.xml nor an rpx file are found whereas qt still starts the kernel. Not sure why it does that to be honest.

**Comment by Shoegzer** [comment]
Thanks @curtisy1.  I tried pointing decaf-sdl to the game directory containing `cos.xml` but I still get the same thing: 
```
[info] Loaded config from /home/shoegzer/.config/decaf/config.toml
[info] Using SDL video driver x11
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[error] Failed to start game
terminate called without an active exception
Aborted (core dumped)
```
Pointing decaf-sdl to the `cos.xml` file specifically, I get this:
```
[info] Loaded config from /home/shoegzer/.config/decaf/config.toml
[info] Using SDL video driver x11
INTEL-MESA: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)
  Major opcode of failed request:  149 ()
  Minor opcode of failed request:  4
  Resource id in failed request:  0x6e0000c
  Serial number of failed request:  235
  Current serial number in output stream:  245
Segmentation fault (core dumped)
```

**Comment by curtisy1** [comment]
Could you maybe try getting another GDB backtrace for this specific exception @Shoegzer? Since I'm not sure where this exception is coming from unfortunately

**Comment by Shoegzer** [comment]
Sure thing, [here](https://pastebin.com/t2W1pMwu) is the backtrace.

**Comment by QuarkTheAwesome** [comment]
Would y'all try reverting https://github.com/decaf-emu/decaf-emu/commit/131aeb14fccff8461a5fd9f2aa5c040ba3880ef5 locally and running whatever gave you the OutOfDateKHR error again, noting your vulkan SDK versions? I have no idea if `decaf-sdl` still works so I'd suggest sticking it out with `decaf-qt`, but hey, you never know.

**Comment by Shoegzer** [comment]
Ah good call @QuarkTheAwesome , I bisected the issue and discovered the cause to be 131aeb14fccff8461a5fd9f2aa5c040ba3880ef5 indeed, as decaf-qt works fine with builds made from any earlier commits.  Vulkan SDK version is same as before i.e. `1.2.170.0`.  

And yes, `decaf-sdl` still doesn't work with builds made earlier than that commit but that seems to be some other issue.

**Comment by QuarkTheAwesome** [comment]
I'm not really sure what to do here, since that function call is marked as noexcept in the vulkan.hpp sources, and yet it does indeed throw an exception. I guess reverting that commit (cc @exjam) is the least bad option for now, since I was the one who saw problems with the old behaviour (as opposed to several unrelated people, as is now).

**Comment by exjam** [comment]
Commit 131aeb1 says:
"libgpu: check return codes, not exceptions, for noexcept vulkan funcs 
Lots of these were made noexcept in Jan 2020, 
KhronosGroup/Vulkan-Hpp@e49f020#diff-7cae1bb20eb3d7d013fd0c88717b70edL60945-R60960"

However if you follow through to the diff on Vulkan-HPP:
"Mark every non-enhanced function with VULKAN_HPP_NOEXCEPT."

The important part here is non-enhanced. It seems decaf is using the enhanced APIs (its the default option) so the noexcept doesnt apply here.

So I went for the half-way approach of checking both except and return code, seems to work for now at least:
https://github.com/decaf-emu/decaf-emu/commit/8d6248469e99c7d075e356a8730848a537f34ece#diff-97d037e55cde27b48c19b9a3dfbf39112357c421bbdefe4b42db26de4e87a625
