### ISSUE TITLE
Decaf freezes when running game

### ISSUE THREAD

**Issue by i-can-not-program** [decaf-emu/decaf-emu#612]
Ubuntu 20.04.2 LTS
When i run New Super Mario Bros. U decaf freezes and gives this error:
QObject::connect: No such slot MainWindow::toggleFullScreen()
QObject::connect:  (sender name:   'actionViewFullScreen')
QObject::connect:  (receiver name: 'MainWindow')
terminate called after throwing an instance of 'vk::OutOfDateKHRError'
  what():  vk::Queue::presentKHR: ErrorOutOfDateKHR

**Comment by exjam** [comment]
You fix this with
https://github.com/decaf-emu/decaf-emu/commit/0cd56a2faa3b0f7d3f447a39ba9ad8449666e2f9

👍
