### ISSUE TITLE
[Linux] Decaf fails to build

### ISSUE THREAD

**Issue by Shoegzer** [decaf-emu/decaf-emu#618]
Decaf fails to build.  Compilation produces messages such as:
```
/home/testing/Desktop/decaf/decaf-emu/libraries/cpptoml/include/cpptoml.h:341:24: error: ‘numeric_limits’ is not a member of ‘std’
  341 |         if (val < std::numeric_limits<int64_t>::min())
      |                        ^~~~~~~~~~~~~~
/home/testing/Desktop/decaf/decaf-emu/libraries/cpptoml/include/cpptoml.h:341:46: error: expected primary-expression before ‘>’ token
  341 |         if (val < std::numeric_limits<int64_t>::min())
      |                                              ^
/home/testing/Desktop/decaf/decaf-emu/libraries/cpptoml/include/cpptoml.h:341:49: error: ‘::min’ has not been declared; did you mean ‘std::min’?
```
Information:
* OS: Linux Mint 20.2 / kernel 5.11
* CPU: Intel i7-10870H
* Compiler: gcc-11.1.0
* CMake: 3.20.2
* Build log: [here](https://pastebin.com/qzmMMpGK)

**Comment by exjam** [comment]
As it seems upstream is no longer maintained i forked it to decaf-emu/cpptoml and fixed this issue https://github.com/decaf-emu/cpptoml/commit/5a6d92731aa8c2d1b2eb2741b1ea982967f77029

So this is fixed with https://github.com/decaf-emu/decaf-emu/commit/42f627c257323a6708116eb8994ca9cb1b4c0e71
