### ISSUE TITLE
Port to vcpkg: lot of libraries detection failing (600337d4)

### ISSUE THREAD

**Issue by mazes-80** [decaf-emu/decaf-emu#633]
find_package(c-ares CONFIG required) ->
CMake Error at CMakeLists.txt (find_package):
  Could not find a package configuration file provided by "c-ares" with any
  of the following names:

    c-aresConfig.cmake
    c-ares-config.cmake

  Add the installation prefix of "c-ares" to CMAKE_PREFIX_PATH or set
  "c-ares_DIR" to a directory containing one of the above files.  If "c-ares"
  provides a separate development package or SDK, be sure it has been
  installed.

To fix this I suggest:
find_package(c-ares CONFIG)
if(NOT c-ares_FOUND)
        pkg_check_modules(c-ares REQUIRED libcares)
endif()

But this is only the first one from a long list. Follow:
- curl: fixable same way as c-ares
- glslang: fixable with cmake (still need to watch further)
- gsl-lite: not available on gentoo default
- imgui: not available in gentoo default
- unofficial-libuv: not available in gentoo default (though libuv is)

**Comment by exjam** [comment]
Just to clarify, this is because you want to be able to use the system libraries instead of using vcpkg? What about the libraries which are not provided by Gentoo?

**Comment by mazes-80** [comment]
1/ I don't know anything about [vcpkg](https://xkcd.com/927/) even it was installed, I think the build system would fail exactly at the same place without noticing anything, not sure though, as said I don't know about it.

2/ Gentoo policy is to link against system libraries whenever possible (adding them to pkg base if unprovided). It would be good to try system libs from build system before trying to link to external things.

3/ Libraries not provided: I don't think it is a gentoo exclusive problem, I think most of linux distros do not ship those (debian does not just as a sample).

4/ specifically about gentoo: there's many phases in the build system for a package, after the download phase, any network access is restricted under the sandbox: so solutions like conan or so-like always fail. I think it's same way in BSD build systems. Keep in mind that what is possible for a build requiring user privs is not always possible in a build supervised by the system package manager

**Comment by exjam** [comment]
Ok I will switch back to using vcpkg (previously Conan) only for those common system libraries such as sdl2, ffmpeg, curl and keep the less widely available libraries as submodules as it was before. So that on Linux you can get away with system package manager + submodules and on Windows vcpkg fills the role that Linux system package manager is doing.

**Comment by exjam** [comment]
Should be fixed with 2b55942eb8c98239279bd6f378cad4095cb6f233 ?

**Comment by mazes-80** [comment]
Le Sun, 23 Jan 2022 06:41:03 -0800,
James ***@***.***> a écrit :

> Should be fixed with 2b55942eb8c98239279bd6f378cad4095cb6f233 ?
> 

Yes it does.

I'll may send more feedback about the way I unbundle some libs if you
are interested.

Another thing: gsl-lite submodule points to
4b796627ad0fa42640f5fdb96f23c4a0d9ee084f, but this commit does not
exist (forced push ... ?), would be nice to point to valid commit
locally I point to 292615c3c2812bdb224843faa41310b30c1e483a.
This enligthens a bug in our gentoo package manager that would be nice
to fix, but still it would be nice to fix consistency in your
repository.

**Comment by exjam** [comment]
Ah yeah that was because gsl-lite was broken on a compiler update, so its currently pointing at decaf-emu/gsl-lite
https://github.com/decaf-emu/gsl-lite/

Although it is fixed upstream now so we could switch back.

**Comment by exjam** [comment]
I switched  gsl-lite and cnl back to their upstream repositories.

https://github.com/gsl-lite/gsl-lite/
https://github.com/johnmcfarlane/cnl/

Please let me know if there are any other improvements I can make for you

**Comment by mazes-80** [comment]
I may make some PR soon, as some linux distros may provide:
catch
cereal
libfmt
pugixml
spdlog

For my builds I use system glslang also, but my approach in cmake files is too messy to be PR able until now.
